### ISSUE TITLE
Using plugin while binding to the class attribute in vue results in unexpected characters error.

### ISSUE THREAD

**Issue by ProjektGopher** [tailwindlabs/prettier-plugin-tailwindcss#1]
When using ? or . inside a :class {} or [] we see errors in the console that for me so far have only referenced lines 1 or 2

![Screen Shot 2022-01-24 at 11 51 00 AM](https://user-images.githubusercontent.com/1688608/150854154-da814cf6-1274-46c9-b602-5acb775d1aa9.png)

![Screen Shot 2022-01-24 at 11 50 09 AM](https://user-images.githubusercontent.com/1688608/150854021-73630d76-1748-490f-80c2-f25765a6cc01.png)

**Comment by bradlc** [comment]
Thanks for reporting @ProjektGopher! This should be fixed in `v0.1.2` 👍
