### ISSUE TITLE
Bug: Not working via pnpm

### ISSUE THREAD

**Issue by JaavierR** [tailwindlabs/prettier-plugin-tailwindcss#10]
As the title says when installing the dependency using the `pnpm add -D prettier-plugin-tailwindcss` command and then running `pnpm prettier --write`, these new rules are not taken into account. I tried deleting the node_modules folder, to reinstall everything and it didn't work either.

After this, I deleted the node_modules folder again to install using `yarn`, thinking that it is the package manager and when I executed the command it did apply the new order rules in all the corresponding files. I don't know what this is due to or if it has to do with the way pnpm handles packages.

My current prettier version is 2.5.1 and the prettier-plugin-tailwindcss is the latest (0.1.3).

**Comment by bradlc** [comment]
Hey @JaavierR. Prettier plugin [autoloading](https://prettier.io/docs/en/plugins.html#using-plugins) is not supported when using pnpm (see https://github.com/prettier/prettier/issues/8474 and https://github.com/prettier/prettier/issues/11008), so you need to add the plugin to your Prettier config manually, for example:

```js
// prettier.config.js
module.exports = {
  plugins: [require('prettier-plugin-tailwindcss')],
}
```

**Comment by brandonpittman** [comment]
Just hit this as well. Might be nice to add this disclaimer to the Readme.

**Comment by mrienstra** [comment]
The README now calls this out, thanks to https://github.com/tailwindlabs/prettier-plugin-tailwindcss/pull/47
