### ISSUE TITLE
v0.2.0 still incompatible with @trivago/prettier-plugin-sort-imports

### ISSUE THREAD

**Issue by jonathanhuang13** [tailwindlabs/prettier-plugin-tailwindcss#104]
**What version of `prettier-plugin-tailwindcss` are you using?** v0.2.0

**What version of Tailwind CSS are you using?** v3.1.8

**What version of Node.js are you using?** v16.16.0

**What package manager are you using?** npm

**What operating system are you using?** macOS

**Describe your issue**

Even with the latest `prettier-plugin-tailwindcss`, Prettier seems unable to sort my imports (with @trivago/prettier-plugin-sort-imports) but it does sort my Tailwind classes. My `.prettierrc.js` file looks like:

```
module.exports = {
  semi: true,
  trailingComma: 'all',
  singleQuote: true,
  printWidth: 120,
  tabWidth: 2,
  plugins: ['@trivago/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
  pluginSearchDirs: false,
};
```

If switch the order of the plugins (e.g. `plugins: ['prettier-plugin-tailwindcss', '@trivago/prettier-plugin-sort-imports']`), then the imports sort but the Tailwind classes do not. If I remove `plugins` and `pluginSearchDirs`, the imports sort but the Tailwind classes do not. These last two scenarios seem expected, but I'm unsure why my current prettierrc.js doesn't work.

I also tried @trivago/prettier-plugin-sort-imports v3.4.0 and I get the same behavior

**Comment by thecrypticace** [comment]
Hey I've got a couple of questions because it appears to be working for me:
- What version of Prettier do you have installed?
- What _language_ are you trying to format? (js, jsx, etc…)
- What file extension are you using?
- Are you developing in Docker by chance? (So you're using like a remote vscode setup?)

---

Here's what I see:

https://user-images.githubusercontent.com/614993/204303466-15fbc559-8047-442f-843e-878db3431530.mov

**Comment by jonathanhuang13** [comment]
Thanks for the quick response. Here's what I'm using:

- Prettier: v.2.8.0
- Language: TSX
- File extension: TSX
- I'm not developing via Docker, just developing locally on VSCode. 

Here's a recording: https://share.cleanshot.com/3N7vHb

I did realize that running `npx prettier --loglevel error --write './**/*.{ts,tsx}'` does work so maybe it's an issue with Prettier's VSCode plugin?

**Comment by jonathanhuang13** [comment]
I ended up uninstalling and reinstalling the VSCode Prettier plugin and things work now. Sorry for the false alarm!

**Comment by reinink** [comment]
@jonathanhuang13 Glad you got it figured out! 🥳
