### ISSUE TITLE
Compatibility with twin.macro package

### ISSUE THREAD

**Issue by drMonro** [tailwindlabs/prettier-plugin-tailwindcss#120]
twin.macro allow me to make separate style file with features of StyledComponent and Tailwind.

Your plugin works perfect, but only for classes inside React component - is there any way to make it work inside ***.styles.tw.ts files?
![Screenshot_137](https://user-images.githubusercontent.com/38846475/215942969-7912372f-fdc1-4229-9da0-8fd8d148acd1.jpg)

**Comment by bradlc** [comment]
Closing in favour of https://github.com/tailwindlabs/tailwindcss/discussions/7558
