### ISSUE TITLE
Cannot find module @prettier/plugin-php

### ISSUE THREAD

**Issue by caplod** [tailwindlabs/prettier-plugin-tailwindcss#124]
**What version of `prettier-plugin-tailwindcss` are you using?**

2.8.4

**What version of Tailwind CSS are you using?**

3.2.4

**What version of Node.js are you using?**

v14

**What package manager are you using?**

Yarn

**What operating system are you using?**

Linux

**Describe your issue**

I installed prettier like this

    yarn global add prettier prettier-plugin-tailwindcss @prettier/plugin-php

I have a .prettierrc

    {
      "plugins": [
        "@prettier/plugin-php",
        "prettier-plugin-tailwindcss"
      ],
      "pluginSearchDirs": false
    }

When I run prettier  I get the following error:

    prettier path/to/some/file.php

    [error] Cannot find module '@prettier/plugin-php'

**Comment by thecrypticace** [comment]
I'm pretty sure the problem here is that you need to install the prettier plugins locally into your project.

**Comment by caplod** [comment]
Thanks for the hint.
I want to use prettier in my editor (neovim) in all my projects. So I dont want to install prettier  and all plugins in every project that I edit.

But after looking in the docs of prettier I found, that you can also define a full path to the global installed plugins.

Right now I have in my ```prettier.config.js```

    module.exports = {
      "plugins": [
        `${process.env.HOME}/.config/yarn/global/node_modules/@prettier/plugin-php`,
        `${process.env.HOME}/.config/yarn/global/node_modules/prettier-plugin-tailwindcss`
      ],
      "pluginSearchDirs": false
    }
 
Now it is working
