### ISSUE TITLE
Sorting for custom colors not working

### ISSUE THREAD

**Issue by leo-mangold** [tailwindlabs/prettier-plugin-tailwindcss#125]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/10632

<div type='discussions-op-text'>

<sup>Originally posted by **leo-mangold** February 19, 2023</sup>
Hey, my tailwind plugin sorts all classes perfectly fine except for classes with custom properties I defined in tailwind config.

### Expected result
```
<header class="relative bg-background text-white">
```
 ### Actual result
```
<header class="bg-background relative text-white">
```

This is especially weird because for my colleague it works perfectly, so we always get a lot of changes in our commits because we both order the classes differently...
 
Is there a setting that I havent found yet or something else?
</div>

**Comment by thecrypticace** [comment]
@leo-mangold I'm not seeing any issues here as far as I can tell. Can you provide either a reproduction or your `tailwind.config.js` file?

**Comment by leo-mangold** [comment]
I can’t give you my tailwind confit rn but it just defines some new colors like background. The problem is that my prettier tailwind plug-in does not recognize these colors apparently because it treats ‘bg-background’ as a custom css class and does not sort it properly

**Comment by reinink** [comment]
@leo-mangold Hey unfortunately without a reproduction we're unable to help.

That said, I suspect what's happening here is that Prettier is maybe not seeing the right Tailwind config. This often happens for projects that have multiple Tailwind configs. Something to try is setting the `tailwindConfig` option in your Prettier config:

```js
module.exports = {
  // ...
  tailwindConfig: '../../my-tailwind-config.js',
}
```

And if that doesn't fix it, again feel free to provide a minimum reproduction as a Git repo and we can have a closer look 👍
