### ISSUE TITLE
Classes on custom Astro components aren't getting sorted

### ISSUE THREAD

**Issue by ni554n** [tailwindlabs/prettier-plugin-tailwindcss#128]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.2.3

**What version of Tailwind CSS are you using?**

v3.2.7

**What version of Node.js are you using?**

v16.14.2 & v18.14.2

**What package manager are you using?**

npm & pnpm

**What operating system are you using?**

Linux

**Reproduction URL**

https://stackblitz.com/edit/node-lf1jgc?file=package.json,src%2Fpages%2Findex.astro
> Run `npm run format` and check the order of the classes in `src/pages/index.astro` file

**Describe your issue**

In a .astro file, Tailwind classes that are specified on default HTML elements are getting sorted correctly, whereas the same classes on a custom Astro component aren't. I have both `prettier-plugin-astro` and `prettier-plugin-tailwindcss` plugin installed.

**Comment by reinink** [comment]
Hey! So you'll need to follow the steps in the readme for working with other Prettier plugins. You can find that here: https://github.com/tailwindlabs/prettier-plugin-tailwindcss#compatibility-with-other-prettier-plugins

I've updated your reproduction, and it's working for me with the addition of the `.prettierrc` file:

https://stackblitz.com/edit/node-hf7jt6?file=.prettierrc

Hope that helps! 👍

**Comment by ni554n** [comment]
Thank you @reinink
I've just tried your fork, but the classes on `<Custom />` remained unchanged like before.

Can you please run `npm run format` again on your fork and confirm it is working?
I've actually had that config file before I submitted the issue, but it didn't work then, so I deleted it to keep the reproduction minimal.

**Comment by selrond** [comment]
Confirming this is still an issue. The sorting doesn’t seem to work in custom (non-native-html) components.

**Comment by ni554n** [comment]
Thanks for adding this quickly. Really appreciate it.
Btw is it still necessary to include `"pluginSearchDirs": false` in the config file? I just tried without it, and seems to be working fine.

**Comment by reinink** [comment]
@ni554n Hey our pleasure, thanks for bring this to our attention 👍
