### ISSUE TITLE
The plugin does not order classes that are specified in a variable outside the className prop

### ISSUE THREAD

**Issue by piedrahitapablo** [tailwindlabs/prettier-plugin-tailwindcss#133]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.2.5

**What version of Tailwind CSS are you using?**

v3.2.7

**What version of Node.js are you using?**

v18.14.2

**What package manager are you using?**

Yarn

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/piedrahitapablo/prettier-tailwind-bug

Steps:

```shell
git clone git@github.com:piedrahitapablo/prettier-tailwind-bug.git
yarn install
yarn format
```

that should show you the git diff for the classes that are reordered

**Describe your issue**

The issue is that this plugin does not order classes that are specified in a variable outside the `className` prop. If you go to the minimal reproduction repo, you can see that I defined two variables (`classes` and `classes2`) that are later used inside the `className` prop, one inside a template string and the other one as the full value of `className` but the plugin does not reorder them. In line 24 I used the [classnames](https://www.npmjs.com/package/classnames) package inside the `className` prop and the plugin picks the classes and reorders them, so it's not an issue with that package.

The behavior I would expect is that the plugin reorders those values. I know that can be tricky in some situations and using [classnames](https://www.npmjs.com/package/classnames) inside the `className` prop should cover most cases.

Finally, if the plugin is working as intended, I think adding some clarification on the docs would be great, just saying that the plugin only reorders the classes defined inside the prop.

Happy to help if I can make a PR, just need some pointers on where to start.

Thanks!

**Comment by nanxiaobei** [comment]
facing the same demand

**Comment by gutisalex** [comment]
same issue when using class variance authority...

**Comment by NorrisWu0** [comment]
Would be great to see support for this. ❤️

**Comment by thecrypticace** [comment]
Hey, we've just merged #155 which provides a way for you to specify additional attributes, functions, and tagged template literals that should be sorted by the plugin. It's available via our insiders build and will be released in the next version of the plugin. We would like to get some feedback on this feature before we release it, so please give it a try and let us know what you think!

To test the new features you can install the insiders build like so:
```
npm install prettier-plugin-tailwindcss@insiders
```

**Comment by ADTC** [comment]
@thecrypticace any way this can piggyback on `tailwindCSS.experimental.classRegex` and also sort the classes in the matching strings? Example config:

```json
"tailwindCSS.experimental.classRegex": ["Class\\s*=\\s*[\"'`]([^\"'`]*)[\"'`]"],
```
which matches `anyClass`, `myClass`, etc. and provides Tailwind Intellisense in the strings.

**Comment by thecrypticace** [comment]
I don't think so. I'd have to add a feature to IntelliSense to support that instead of the Prettier plugin. The problem is the regexes aren't necessarily "specific" enough to cover what constitutes a proper class list (at least if you're using the single string version) and I worry that applying automatic sorting to them could end up mangling your code which would obviously be bad.

I'll add an internal note to look into it tho.
