### ISSUE TITLE
Bug in he GitHub ReadME.md

### ISSUE THREAD

**Issue by i4rv** [tailwindlabs/prettier-plugin-tailwindcss#134]
### In the first code snippet,  it states the filename as **prettier.config.js** instead of _**tailwindcss.config.js**_
```
**// prettier.config.js**
module.exports = {
  plugins: [require('prettier-plugin-tailwindcss')],
}
```

### In the second code snippet, it states the property name as **tailwindConfig** instead of _**twConfig**_
```
// prettier.config.js
module.exports = {
  **tailwindConfig**: './styles/tailwind.config.js',
}
```

**Comment by adamwathan** [comment]
Hey! There are no mistakes here, both of those things are correct as is.

**Comment by i4rv** [comment]
Sorry, A very rookie mistake 🙏
