### ISSUE TITLE
implement sorting in all existing files in project

### ISSUE THREAD

**Issue by MrNaifpp** [tailwindlabs/prettier-plugin-tailwindcss#14]
once install the package how to implement sorting in all files in the project

**Comment by reinink** [comment]
Hey!

Are you saying that you'd like to update the class order in all the existing files in your project at once? This is possible with Prettier itself (assuming you also have this plugin installed).

You can do something like this in the root of your project:

```
prettier --write .
```

You can read more about that here: https://prettier.io/docs/en/cli.html

Hope that helps 👍
