### ISSUE TITLE
Support Tailwind v3.3.0 TS config file

### ISSUE THREAD

**Issue by MrSucik** [tailwindlabs/prettier-plugin-tailwindcss#145]
### What version of prettier-plugin-tailwindcss are you using?

**^0.2.2**

### What version of Prettier are you using?

**^2.8.3**

### What version of Tailwind CSS are you using?

**^3.3.0**

### What version of Node.js are you using?

**v18.10.0**

### What package manager are you using?

**npm 8.19.2**

### What operating system are you using?

**macOS**

### Describe your issue

With the introduction of Tailwind CSS 3.3.0, it is now possible to use custom theme extensions from the Tailwind config file in TypeScript. However, after updating to the specified versions, I've noticed that the prettier-plugin-tailwindcss is unable to recognize these custom theme extensions in the config file, causing the plugin to not format Tailwind CSS classes correctly.

### Steps to reproduce:

- Update to Tailwind CSS ^3.3.0, Prettier ^2.8.3, and prettier-plugin-tailwindcss ^0.2.2
- Add custom theme extensions to the Tailwind config file in TypeScript format
- Run `npm run format` or use the Prettier extension in the code editor

Observe that the Tailwind CSS classes with custom theme extensions remain unformatted
I expected the plugin to recognize and correctly format the custom theme extensions from the Tailwind config file in TypeScript. - This issue might be related to the changes introduced in Tailwind CSS 3.3.0 and the plugin's compatibility with the new features.

**Comment by adamwathan** [comment]
Hey! Can you share your Prettier config file? I suspect you might have a `tailwindConfig` option in there that's pointing to a different path — the `tailwind.config.ts` file should be picked up automatically as long as there is no explicit configuration for a different path.

**Comment by michaelschufi** [comment]
Hi @adamwathan 

For me, if I have the following `.prettierrc.js` js file

```js
module.exports = {
  trailingComma: 'all',
  singleQuote: true,
  plugins: [require('prettier-plugin-tailwindcss')],
  tailwindConfig: './tailwind.config.ts',
};
```

 and run prettier, I get the following errors:

```
.eslintrc.js
[error] .eslintrc.js: /home/michael/myrepo/app/tailwind.config.ts:1
[error] import { config } from './tailwind/config';
[error] ^^^^^^
[error] 
[error] SyntaxError: Cannot use import statement outside a module
[error]     at Object.compileFunction (node:vm:360:18)
[error]     at wrapSafe (node:internal/modules/cjs/loader:1055:15)
[error]     at Module._compile (node:internal/modules/cjs/loader:1090:27)
[error]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
[error]     at Module.load (node:internal/modules/cjs/loader:1004:32)
[error]     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
[error]     at Module.require (node:internal/modules/cjs/loader:1028:19)
[error]     at nx.exports (/home/michael/myrepo/app/node_modules/.pnpm/prettier-plugin-tailwindcss@0.1.13_prettier@2.8.7/node_modules/prettier-plugin-tailwindcss/dist/index.js:134:2647)
[error]     at Object.parse (/home/michael/myrepo/app/node_modules/.pnpm/prettier-plugin-tailwindcss@0.1.13_prettier@2.8.7/node_modules/prettier-plugin-tailwindcss/dist/index.js:146:4138)
[error]     at Object.parse (/home/michael/myrepo/app/node_modules/.pnpm/prettier@2.8.7/node_modules/prettier/index.js:7515:23)
.prettierrc.js
[error] .prettierrc.js: /home/michael/myrepo/app/tailwind.config.ts:
```

So, it seems that the plugin is unable to compile to JS before importing the config.

**Comment by bradlc** [comment]
Hey @MrSucik. As Adam mentioned the plugin supports TS config files since `v0.2.6`. Check that you're on the latest version and that you don't have the `tailwindConfig` option configured to point to a different config file.

If you're still having problems after that then please open a new issue and include a GitHub repository that we can clone to immediately reproduce the issue.
