### ISSUE TITLE
Classes inside Astro's dynamic HTML don't recognise tailwind extended colors

### ISSUE THREAD

**Issue by vanntile** [tailwindlabs/prettier-plugin-tailwindcss#154]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.2.8

**What version of Tailwind CSS are you using?**

v3.3.2

**What version of Node.js are you using?**

v18.7.0

**What package manager are you using?**

npm

**What operating system are you using?**

Linux, Debian-based

**Reproduction URL**

[vanntile/prettier-plugin-tailwind-test](https://github.com/vanntile/prettier-plugin-tailwind-test)

**Describe your issue**

Using VSCode and the Astro extension v1.0,4 and Prettier extension v9.12.0, and automatic file formatting of Astro files (like below or [here](https://github.com/vanntile/prettier-plugin-tailwind-test/blob/master/.vscode/settings.json)), the code gets formatted differently in the editor than the CLI.

```
"[astro]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSaveMode": "file",
  },
```

Moreover, as one can see in the index file (or code block below), the class string inside Astro's dynamic HTML is not sorted identically with the one in a plain HTML element. More specifically, the `-brand` classes, created from extending the Tailwind color palette, are not recognized and sorted immediately after the `not-tw` class, which is not part of Tailwind.

```astro
---
---

<p
  class="not-tw h-12 bg-transparent text-brand ring-brand-secondary will-change-transform"
>
  Hello
</p>
{
  (
    <p class="not-tw text-brand ring-brand-secondary h-12 bg-transparent will-change-transform">
      Goodbye
    </p>
  )
}
```

Running `npm run format`, one can see that prettier formats both strings the same way, but in the editor, they are not both recognized. The minimal example above has all the settings needed. This is irrespective if one is using the Tailwind VSCode extension or not.

In the end, this does not allow one to have prettier as a linting pre-commit check and use automatic file formatting at the same time.

**Comment by Princesseuh** [comment]
Hello! For expressions we just use Prettier's embed feature. I'm not too sure how else we could handle this, Astro expressions are essentially JSX, apart from very small differences.

We can definitely pass the options, though I thought Prettier would do it itself...

**Comment by thecrypticace** [comment]
I found the source of the problem in Astro's prettier plugin and have opened a PR to fix it:
https://github.com/withastro/prettier-plugin-astro/pull/339

I'm going to close this issue for now and the problem can be tracked over there.
