### ISSUE TITLE
Incompatible with `prettier-plugin-twig-melody`

### ISSUE THREAD

**Issue by perruche** [tailwindlabs/prettier-plugin-tailwindcss#16]
Hello,

Regarding this part of the README.
> This means this plugin is incompatible with other Prettier plugins that are using the same APIs.
> ...
> If you discover any other incompatibilities, open an issue and hopefully we can figure out a way to make it work.

This plugin does not work with `*.twig` files, with [prettier-plugin-twig-melody](https://github.com/trivago/prettier-plugin-twig-melody)

prettier version: 2.5.1
prettier-plugin-twig-melody version: 0.4.6
tailwindcss version: 2.2.19

My .prettierrc.js 
```
module.exports = {
  bracketSpacing: true,
  printWidth: 100,
  semi: true,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'es5',
  useTabs: false,
  vueIndentScriptAndStyle: true,
  htmlWhitespaceSensitivity: 'ignore',
  twigPrintWidth: 100,
  twigMultiTags: ['html_element,end_html_element', 'with,endwith'],
  tailwindConfig: './tailwind.config.js'
};
```

Only the settings from the twig plugin are applied when running prettier, class names stay in the same order.

**Comment by perruche** [comment]
The source from the plugin does not have a parser for Twig:
https://github.com/tailwindlabs/prettier-plugin-tailwindcss/blob/main/src/index.js#L349

If a different approach can be taken to use this tailwind prettier plugin with twig files, i'm all ears

Anyway this plugin is 🔥

**Comment by florianbouvot** [comment]
Same request for me, how to make this plugin work with twig files? 🤔 #PrettierBeginner

**Comment by davidhellmann** [comment]
@florianbouvot 
Hm, `.html` it works fine  but on `.html.twig` not. 
I'm using PHPStorm. Did you something special? :D

**Comment by reinink** [comment]
Hey! Thanks for reporting this. I've created a new issue (#31) dedicated to keeping track of Prettier plugins that are not compatible with this plugin. Closing this issue in favor of that 👍

Please feel free to post this incompatibility with `prettier-plugin-twig-melody` in that issue, it would be great to have it there for quick reference.

**Comment by kerns** [comment]
I posted the same question in the discord but worried it's too specific to get an answer there.

Just wondering if there is a way in VSC to enjoy class sorting via `prettier-plugin-tailwindcss` inside of `.twig` files, ...but without losing basic twig syntax highlighting...which would be lost if I simply asked VSC to treat `.twig` as `.html`.

**Comment by sweetroll** [comment]
Is it possible to set this plugin as the parser of twig files without having to use the HTML parser too?

**Comment by florianbouvot** [comment]
@kerns did you find a solution?
