### ISSUE TITLE
Calling prettier with . doesn't run tailwind plugin

### ISSUE THREAD

**Issue by hugollm** [tailwindlabs/prettier-plugin-tailwindcss#160]
**What version of `prettier-plugin-tailwindcss` are you using?**

prettier-plugin-tailwindcss 0.2.7

**What version of Tailwind CSS are you using?**

tailwindcss 3.3.1

**What version of Node.js are you using?**

node 20.0.0

**What package manager are you using?**

pnpm 8.5.0

**What operating system are you using?**

Ubuntu 22.04 under Windows 10 (WSL2).

**Reproduction URL**

I'm trying to help but this is asking too much. Feel free to close if it's required.

## **Describe your issue**

Calling prettier with `.` doesn't run tailwind plugin.

```
pnpm prettier --config prettier.tailwind.js --write .
```

It only works if I specify the file:

```
pnpm prettier --config prettier.tailwind.js --write components/icons.jsx
```

---

This is my config:

```js
// workaround for tailwind plugin that doesn't seem to play nice with others
let config = require("./prettier.base.js");

module.exports = Object.assign(config, {
  plugins: [require("prettier-plugin-tailwindcss")],
});
```

I have a separate config file just for tailwind so it doesn't break other plugins. Config base is just:

```js
module.exports = {
  printWidth: 120,
};
```

**Comment by thecrypticace** [comment]
@hugollm I tried creating a repro from these instructions but I'm not seeing the behavior you are seeing:

<img width="365" alt="Screenshot 2023-05-15 at 10 38 23" src="https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/614993/606a94eb-bd59-4f8a-ad82-40c7f163fb6b">

I'm not sure I can help any further without more information or a reproduction. There is one more thing I want to try — see if the behavior is specific to WSL2. I'll give that a look later today.

As an aside, what plugins are you using that don't work with the Tailwind prettier plugin?

**Comment by thecrypticace** [comment]
I checked against WSL2 and didn't see the described behavior. In this case it's quite likely to be something specific to your setup.

**Comment by hugollm** [comment]
> As an aside, what plugins are you using that don't work with the Tailwind prettier plugin?

@trivago/prettier-plugin-sort-imports

> In this case it's quite likely to be something specific to your setup.

I was feeding a list of git changed files in a pre-commit hook. I didn't say it here because I was able to reproduce manually outside the script (with the commands I pasted here).

But now that I think back on it, there was a `.prettierignore` involved. Prettier doesn't ignore unsupported files when feeding a list to it, so I had some shady rules there.

If you weren't able to reproduce, it could very well be a subtle bug in `.prettierignore`. Since we lack information I'll just close this issue then. Not really up for investigating this further right now (maybe in the future). Sorry for the trouble 😅

**Comment by thecrypticace** [comment]
No worries! `@trivago/prettier-plugin-sort-imports` should definitely work with the plugin. We even have tests for it. Any chance you could open an issue (if you have time) about what's not working with it?

**Comment by hugollm** [comment]
That's interesting. Whenever I put them both together, one of them didn't run. I tried for a good couple hours I think. I gave up when I found some comments of people with the same issue. 🤔 

Maybe I just missed something. If I can reproduce it again I'll upload the minimal repo thing and create the issue.

**Comment by thecrypticace** [comment]
@hugollm something to try is use the latest release (v0.3.0). It may have been a name vs. require thing which should be fixed.

**Comment by hugollm** [comment]
Just tested `0.3.0` and it worked nicely with the sort imports plugin! 🙌
Was also able to reproduce the issue again with `0.2.7`. So it did have an issue.

Thanks for the help there! 😀
