### ISSUE TITLE
Trouble using plugin with NextJS in VSCode

### ISSUE THREAD

**Issue by rohitsodhia** [tailwindlabs/prettier-plugin-tailwindcss#172]
**What version of `prettier-plugin-tailwindcss` are you using?**

2.2.12

**What version of Tailwind CSS are you using?**

3.3.2

**What version of Node.js are you using?**

18.15.0

**What package manager are you using?**

npm

**What operating system are you using?**

Ubuntu

**Reproduction URL**

https://github.com/rohitsodhia/prettier-plugin-test

**Describe your issue**

In VS Code, when I try to format with Prettier, I get
```
Cannot find module '{my path}/node_modules/tailwindcss/stubs/defaultConfig.stub.js'
```

**Comment by thecrypticace** [comment]
Hey! I believe you're indirectly using the wrong prettier plugin. You're using `prettier-plugin-tailwind` which isn't compatible with Tailwind CSS anymore. The correct plugin to install and use is `prettier-plugin-tailwindcss` (note the additional `css` at the end of the name).
