### ISSUE TITLE
Prettier cannot save file with extended prettier-plugin-tailwindcss plugin

### ISSUE THREAD

**Issue by ioofy** [tailwindlabs/prettier-plugin-tailwindcss#173]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.1.10

**What version of Tailwind CSS are you using?**

v3.0.24

**What version of Node.js are you using?**

v16.0.0

**What package manager are you using?**

Yarn

**What operating system are you using?**

macOS

**Reproduction URL**
-

**Describe your issue**

Prettier cannot save a file with extended this plugin, it got a error on output

you can see it : 

<img width="1710" alt="Screenshot 2023-06-21 at 08 56 49" src="https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/77242429/ef446996-de15-4178-ba4f-90410a30d480">

When commenting out the plugin its working fine again.

Do you know what happen in here?

**Comment by ioofy** [comment]
idk what happen here. But i rechange my prettier config into
```

{
  "printWidth": 80,
  "bracketSameLine": true,
  "bracketSpacing": false,
  "tabWidth": 2,
  "useTabs": false,
  "singleQuote": false,
  "trailingComma": "all",
  "plugins": ["prettier-plugin-tailwindcss"],
}
```

its working fine again both plugin and prettier

**Comment by lsbbd** [comment]
Looks like the problem comes from the prettier plugin of vs code

https://github.com/prettier/prettier-vscode/issues/3036

**Comment by ioofy** [comment]
> Looks like the problem comes from the prettier plugin of vs code
> 
> [prettier/prettier-vscode#3036](https://github.com/prettier/prettier-vscode/issues/3036)

thats right, but i just re change my config from cjs into .prettierrc files, i dont know what happening i debuging another json in my vscode but when change it, working as well again.
