### ISSUE TITLE
Updating prettier to 3.0.0 breaks the plugin.

### ISSUE THREAD

**Issue by JustFly1984** [tailwindlabs/prettier-plugin-tailwindcss#178]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.3.0

**What version of Tailwind CSS are you using?**

v3.3.2

**What version of Node.js are you using?**

v18.16.1

**What package manager are you using?**

Yarn

**What operating system are you using?**

macOS

**Describe your issue**

Prettier 3.0.0 released. I've tested an update, and errors coming from tailwindcss plugin. reverting back to prettier@2.8.8 resolves an issue.

**Comment by thevuong** [comment]
Duplicate #176
