### ISSUE TITLE
Prettier v3 doesn't support option "pluginSearchDirs": false

### ISSUE THREAD

**Issue by TristanBrotherton** [tailwindlabs/prettier-plugin-tailwindcss#187]
**What version of `prettier-plugin-tailwindcss` are you using?**
0.4.1

**What version of Tailwind CSS are you using?**
3.3.3

**What version of Node.js are you using?**
18.16.0

**What package manager are you using?**
NPM

**What operating system are you using?**
OSX

**Describe your issue**

I am aware Prettier v3 support is lacking and is a [known issue,](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/186) but I wanted to flag that when using Prettier v3 it will complain about the option `pluginSearchDirs` if it is set as per the prettier-plugin-tailwindcss documentation outputting the error:

`[warn] Ignored unknown option { pluginSearchDirs: false }.`

**Comment by thecrypticace** [comment]
Yeah, we need to rework the readme to more clearly define up-to-date instructions when using Prettier v3.

In this case it's not an error — just a warning — since it does not stop the build / formatting process. But I'll leave this open as a reminder to do a second pass on the readme this coming week.

**Comment by thecrypticace** [comment]
I've tweaked the readme a bit to hopefully better address this. Thanks!

**Comment by vhscom** [comment]
Those landing here be sure you also check your prettier config file as noted in the docs. Some examples of things you may need to change to upgrade to prettier 3.x can be found detailed here: https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/186#issuecomment-1642423932
