### ISSUE TITLE
is it possible to remove additional spaces between classes?

### ISSUE THREAD

**Issue by 72fcosta** [tailwindlabs/prettier-plugin-tailwindcss#200]
is it possible to remove additional spaces between classes?

**Comment by thecrypticace** [comment]
Hey! We've thought about doing this but we intentionally do not this right now. It can result in incorrect changes to code for some languages and break assumptions Prettier makes. This is all due to implementation details on how languages and Prettier itself are built.

**Comment by 72fcosta** [comment]
Thanks :D

**Comment by AsadpourMohammad** [comment]
What about bringing all the additional white space to the end of the string? It would solve the code length problem, and it would be easier to clean the white space.

**Comment by ArturBaybulatov** [comment]
Related discussion:
https://github.com/tailwindlabs/tailwindcss/issues/7559
