### ISSUE TITLE
ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by uktamka** [tailwindlabs/prettier-plugin-tailwindcss#201]
**What version of `prettier-plugin-tailwindcss` are you using?**

0.5.1

**What version of Tailwind CSS are you using?**

v3.3.3

**What version of Node.js are you using?**

v20.5.1

**What package manager are you using?**

pnpm

**What operating system are you using?**

Windows

**Reproduction URL**
HAS NOT

**Describe your issue**

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

**Comment by thecrypticace** [comment]
Fixed in #199 and now available as v0.5.2
