### ISSUE TITLE
problems with modules

### ISSUE THREAD

**Issue by luas10c** [tailwindlabs/prettier-plugin-tailwindcss#202]
I'm using version ^0.5.2 for next.js

![image](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/66514698/e757ecaa-77a3-4451-bc92-b34ef67615fe)
![image](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/66514698/962aba7f-3042-461f-a0bf-25ee40b4a9aa)

needs support for esmodules and commonjs, otherwise on old configurations it breaks.

**Comment by thecrypticace** [comment]
Hey! So the new plugin is Prettier v3+ and ESM-only because it uses functionality not available to Common JS (top-level await). You should be able to use `"prettier-plugin-tailwindcss"` in your config without using require.

**Comment by luas10c** [comment]
Previous versions have not been fully removed.
I believe it is still viable to have a bundle for commonjs
