### ISSUE TITLE
Can't read file preflight.css after upgrade to v0.5.2

### ISSUE THREAD

**Issue by YannicEl** [tailwindlabs/prettier-plugin-tailwindcss#203]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.5.2

**What version of Tailwind CSS are you using?**

Don't have tailwind installed

**What version of Node.js are you using?**

v20.4.0 also tried 18.13.0

**What package manager are you using?**

pnpm

**What operating system are you using?**

Windows 11 64

**Reproduction URL**

https://stackblitz.com/edit/stackblitz-starters-grpqqn?file=package.json

**Describe your issue**

Problem occurred once i upgraded to v0.5.2, v0.4.1 worked fine.

When running `prettier --write .` in the reproduction project I get the following error for every file prettier wants to format:

`Error: ENOENT: no such file or directory, open '\C:\Users\user\git\vue-useForm\node_modules\.pnpm\prettier-plugin-tailwindcss@0.5.2_prettier-plugin-organize-imports@3.2.3_prettier@3.0.1\node_modules\prettier-plugin-tailwindcss\dist\css\preflight.css' `

![image](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/42739553/44efa75e-298a-438e-99a7-4784d704b731)

When following the path, the file `preflight.css` does indeed exist so I am guessing it has something to do with how pnpm symlinks `node_modules`. Furthermore, it seems that the problem only occurred on windows. Running `prettier --write .` in the stackblitz example works and I have a similar setup running on an ubuntu github action which also works correctly. In order to reproduce the issue one would have to download the stackblitz example and run it on a windows machine.

I'm happy to help debug this issue on my windows machine.

**Comment by YannicEl** [comment]
I get the same error when installing dependencies with `npm` so I'm confident `pnpm` is not the problem here.

After some investigation I found the code that throws the error:

![image](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/42739553/bc47d916-8fe3-4433-abcc-c3140a3dfb1f)
This is a screenshot from `node_modules/prettier-plugin-tailwindcss/dist/index.mjs`. 

I think the problem has something to do with the CJS interop fixes for `__filename` and `__dirname` introduced in this [commit](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/commit/985302fca4b5222c3b6c6974b46afeafb60ff5e4) not working as intended on windows.

`__dirname` has the value `test/test.css/C:/Users/bamio/Downloads/stackblitz-starters-grpqqn%20(2)/node_modules/.pnpm/prettier-plugin-tailwindcss@0.5.2_patch_hash=d33hsm7udv6cddqwwjfqsxcbpm_prettier@3.0.1/node_modules/prettier-plugin-tailwindcss/dist`.

The `test/test.css` at the beginning is the path to the file that is being formated and the rest is the absolut path to the libaries dist foder in `node_modules`.

**Comment by YannicEl** [comment]
Managed to fix it with the solution outlined here: https://stackoverflow.com/a/55944697/14543877
Will make a PR

**Comment by YannicEl** [comment]
PR #204

**Comment by petercpwong** [comment]
Regression is back in `v0.5.8`
