### ISSUE TITLE
Next lint command using prettier with eslint gives "require()" error on console

### ISSUE THREAD

**Issue by AugustoWerlang** [tailwindlabs/prettier-plugin-tailwindcss#208]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.5.3

**What version of Tailwind CSS are you using?**

v3.3.3

**What version of Node.js are you using?**

v18.17.0

**What package manager are you using?**

pnpm

**What operating system are you using?**

Windows 10

**Reproduction URL**

https://github.com/AugustoWerlang/prettier-pluguin-tailwindcss-bug

**Describe your issue**

In previous version 4.1 worked as expected, but when i updated to 5.3 this error showed up in the console:

```powershell
> next lint

require() of ES Module C:\Users\Guto\prettier-pluguin-tailwindcss-bug\node_modules\.pnpm\prettier-plugin-tailwindcss@0.5.3_prettier@3.0.2\node_modules\prettier-plugin-tailwindcss\dist\index.mjs not supported.
Instead change the require of C:\Users\Guto\prettier-pluguin-tailwindcss-bug\node_modules\.pnpm\prettier-plugin-tailwindcss@0.5.3_prettier@3.0.2\node_modules\prettier-plugin-tailwindcss\dist\index.mjs to a dynamic import() which is available in all CommonJS modules.      
Occurred while linting C:\Users\Guto\prettier-pluguin-tailwindcss-bug\src\app\layout.tsx:1
Rule: "prettier/prettier"
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by hilja** [comment]
I've got the same error in my Remix project.

**Comment by hilja** [comment]
I had this in in my `prettier.config.js`:

```
module.exports = {
  plugins: [require('prettier-plugin-tailwindcss')],
}
```

I removed the require and it works:

```
module.exports = {
  plugins: ['prettier-plugin-tailwindcss'],
}
```

**Comment by thecrypticace** [comment]
@AugustoWerlang You have `require('prettier-plugin-tailwindcss')` in your prettier config and it needs to be changed to remove the require. Ps. you also have a typo in the config file.

The config file should look like this — as @hilja pointed out above:
```js
module.exports = {
  plugins: ['prettier-plugin-tailwindcss'],
}
```

**Comment by thecrypticace** [comment]
@lommaj Do you have a reproduction I can look at?

**Comment by lommaj** [comment]
sorry I just tried to add this to my latest project and VSCode was spitting out the error posted above.

I saw it was a new issue so I added my comment.  I have a big monorepo so I would have to try to make a tiny repo and see if I can reproduce.

I can try again later, I already removed the package.

**Comment by lommaj** [comment]
ok my bad - project was using prettier config in the package.json instead of a config file, moving everything to the config file fixed it.

**Comment by thecrypticace** [comment]
@lommaj oh that's good to know — that should still work. I'll give that a test.

**Comment by thecrypticace** [comment]
@lommaj just tested and that seems to also work fine — even if moving it to the config file fixed it a repro would be handy (if you can find the time to provide one) just so I can figure out what is/was going on. If you do get around to doing that could you open a separate issue with it?

Closing this as the parent issue should be resolved with the change in my comment from earlier.

**Comment by sarayourfriend** [comment]
This might help either debug the issue _or_ provide guidance for other folks stuck on this problem. I upgraded prettier and this plugin recently in WordPress/openverse and received the following error messages:

```
[error] require() of ES Module /home/sara/projects/openverse/node_modules/.pnpm/prettier-plugin-tailwindcss@0.5.3_prettier@3.0.2/node_modules/prettier-plugin-tailwindcss/dist/index.mjs not supported.
[error] Instead change the require of /home/sara/projects/openverse/node_modules/.pnpm/prettier-plugin-tailwindcss@0.5.3_prettier@3.0.2/node_modules/prettier-plugin-tailwindcss/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.
[error] require() of ES Module /home/sara/projects/openverse/node_modules/.pnpm/prettier-plugin-tailwindcss@0.5.3_prettier@3.0.2/node_modules/prettier-plugin-tailwindcss/dist/index.mjs not supported.
[error] Instead change the require of /home/sara/projects/openverse/node_modules/.pnpm/prettier-plugin-tailwindcss@0.5.3_prettier@3.0.2/node_modules/prettier-plugin-tailwindcss/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.
```

Following the guidance in the last message, changing the plugin `require` to an `import` fixed it. Removing the require completely did _not_ fix the issue. Here is the diff of our configuration change that resolved the error:

```
diff --git a/prettier.config.js b/prettier.config.js
index 33f7b4fda..ec8f8ad0d 100644
--- a/prettier.config.js
+++ b/prettier.config.js
@@ -14,7 +14,7 @@ module.exports = {
     {
       files: ["frontend/**/*"],
       options: {
-        plugins: [require("prettier-plugin-tailwindcss")],
+        plugins: [import("prettier-plugin-tailwindcss")],
         tailwindConfig: "frontend/tailwind.config.ts",
         vueIndentScriptAndStyle: false,
       },
```

**Comment by victorcbb** [comment]
> I had this in in my `prettier.config.js`:
> 
> ```
> module.exports = {
>   plugins: [require('prettier-plugin-tailwindcss')],
> }
> ```
> 
> I removed the require and it works:
> 
> ```
> module.exports = {
>   plugins: ['prettier-plugin-tailwindcss'],
> }
> ```

That's working for me
