### ISSUE TITLE
Mismatch with Github Action using Prettier

### ISSUE THREAD

**Issue by megasanjay** [tailwindlabs/prettier-plugin-tailwindcss#21]
I'm using a [Github action](https://github.com/wearerequired/lint-action) to format any code that my team pushes up using prettier. It's incredibly useful but I also have a local instance of Prettier installed via my node package.json and in VScode. 

There seems to be a mismatch in how the two versions of prettier handle a custom font class. 

VSCode returns this:
```html
<div class="font-inter flex w-full flex-row items-center justify-between"></div>
```

My github action returns this:
```html
<div class="flex w-full flex-row items-center justify-between font-inter "></div>
```

Is there any reason for this discrepancy? 

Actually, I just realized it is more than just the font classes.  There are more classes where whatever ordering the styles aren't in sync. I do have this plugin in my dev dependencies so I t should be getting installed. 
Adding the commit log for this to show all the changes: https://github.com/fairdataihub/SODA-for-COVID-19-Research/commit/d4b3dc6642115bbb3f0ce3ba7c47038c2edcb563

**Comment by milanbgd011** [comment]
This might be linked to #19 in some way.

**Comment by sdavids** [comment]
Maybe the environments have different `Set` implementations and thereby the iteration order is different?

https://github.com/tailwindlabs/prettier-plugin-tailwindcss/blob/a3dbd89560a8eee1cfec073ab6369cc393cd72a2/src/index.js#L65

Have not verified it though ..

**Comment by megasanjay** [comment]
Is there any way I can test this? I'm more than happy to run some stuff on my end to test the implementation if needed.

**Comment by bradlc** [comment]
Hey @megasanjay. Since you don't seem to have a Prettier config file, I have a feeling this is related to an issue with config resolution that has been resolved in #62. Please could you upgrade the plugin to `v0.1.8` and let me know if that fixes your issue?

**Comment by megasanjay** [comment]
@bradlc Thank you for the updates. I added a `.prettierrc` and added some prettier plugins to my eslint config. It seems to have solved the issue. Thank you :)

**Comment by milanbgd011** [comment]
This is also resolved for me. Thanks guys!
