### ISSUE TITLE
Usage of this plugin without a standalone configuration file

### ISSUE THREAD

**Issue by virtuallyunknown** [tailwindlabs/prettier-plugin-tailwindcss#210]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.5.3

**What version of Tailwind CSS are you using?**

v3.3.3

**What version of Node.js are you using?**

v20.5.1

**What package manager are you using?**

npm

**What operating system are you using?**

Linux

**Describe your issue**

Greetings!

I've been using this plugin for a while along with [Prettier Formatter for Visual Studio Code](https://github.com/prettier/prettier-vscode) for a while now and I didn't have any issues. Basically I just npm installed it in any project I like and it just worked great, no issues whatsoever. Well, I just recently installed it on another project but it didn't work anymore, which prompted me to read the documentation.

It appears that you need to have a `prettier.config.js` (or similar) in project root or elsewhere, something that didn't appear to be necessary before (?) or it just worked without it anyway:

```js
// prettier.config.js
module.exports = {
  plugins: ['prettier-plugin-tailwindcss'],
}
```

But this is causing two issues for me personally:

1. I am not big fan of having configuration files in all of my projects, [so instead I define my prettier settings in `settings.json`](https://github.com/prettier/prettier-vscode#visual-studio-code-settings). These are essentially the global VSCode user settings for the Prettier VSCode formatter extension. This isn't the recommended way of configuring [as mentioned in their documentation](https://github.com/prettier/prettier-vscode#configuration), but nevertheless I never had any issues with it, nor when I used it along with prettier-plugin-tailwindcss.
2. My second issue is that if I create `prettier.config.js` in project root then the tailwind plugin starts working, but that also means all my other settings are gone and I have to copy-paste all my prettier settings from `settings.json` into the newly created `prettier.config.js` file.

Is there any way to get around this problem and just keep things as they used to be?

Thank you.

**Comment by thecrypticace** [comment]
Hey! So, a prettier config either in as a key in `package.json`, a `prettier.config.js`, or other similarly supported file is required **because of Prettier v3**. This is directly attributable to Prettier v3. When Prettier upgraded from v2 to v3 they removed plugin autoloading (iirc because it was incompatible with some package managers). You are now required to explicitly list plugins in a config file. This is the reason a config is necessary. I'm afraid there's nothing we can do about this. Sorry.

**Comment by virtuallyunknown** [comment]
> Hey! So, a prettier config either in as a key in `package.json`, a `prettier.config.js`, or other similarly supported file is required **because of Prettier v3**. When Prettier upgraded from v2 to v3 they removed plugin autoloading (iirc because it was incompatible with some package managers). You are now required to explicitly list plugins in a config file. This is the reason a config is necessary. I'm afraid there's nothing we can do about this. Sorry. :(

I tried creating a common configuration file living outside of projects which I then load with `"prettier.configPath": "/home/user/.config/.prettierrc.json"` and I put my settings in there. But the problem is prettier VSCode will silently fail if `"plugins": ["prettier-plugin-tailwindcss"]` is present in this very same `.prettierrc.json` file.

This is so frustrating, but I understand there is nothing you can do about this, and I appreciate you reaching out to help. Thanks!
