### ISSUE TITLE
Using React Component with className prop in Astro, this plugin doesn't work

### ISSUE THREAD

**Issue by enk0de** [tailwindlabs/prettier-plugin-tailwindcss#213]
**What version of `prettier-plugin-tailwindcss` are you using?**
0.5.4

For example: v0.1.7

**What version of Tailwind CSS are you using?**
3.0.24

For example: v3.0.22

**What version of Node.js are you using?**
v18+

For example: v12.0.0

**What package manager are you using?**
yarn

For example: npm, Yarn

**What operating system are you using?**
macOS

For example: macOS, Windows

**Reproduction URL**
-

A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

**Describe your issue**
when i use React Component that has `className` prop for taking additional classes **in .astro file** , this plugin cannot detect `className` in astro file.

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

**Comment by thecrypticace** [comment]
Hey I've merged a fix for this in #215 and it'll be available via our insiders build shortly:
```
npm install prettier-plugin-tailwindcss@insiders
```

I'll push out a proper release later this week. Thanks for reporting it!
