### ISSUE TITLE
Cannot sort classes in nunjucks

### ISSUE THREAD

**Issue by coxde** [tailwindlabs/prettier-plugin-tailwindcss#216]
**What version of `prettier-plugin-tailwindcss` are you using?**

0.5.4

**What version of Tailwind CSS are you using?**

3.3.3

**What version of Node.js are you using?**

v20.6.1

**What package manager are you using?**
npm

**What operating system are you using?**

Linux

**Reproduction URL**

https://github.com/coxde/prettier-plugin-tailwindcss-nunjucks-reproduction

**Describe your issue**

As shown in the reproduction repo, when I use [.njk](https://github.com/coxde/prettier-plugin-tailwindcss-nunjucks-reproduction/blob/main/src/test.njk) instead of [.html](https://github.com/coxde/prettier-plugin-tailwindcss-nunjucks-reproduction/blob/main/src/index.html), this plugin cannot sort or format file.

Just in case, I use this VScode plugin to support Nunjucks: https://github.com/edheltzel/nunjucks-for-visual-studio-code

Related Discussion: https://github.com/tailwindlabs/tailwindcss/discussions/11949

**Comment by hungtcs** [comment]
+1

**Comment by thecrypticace** [comment]
Hey! So for third-party languages not supported by Prettier itself — like Nunjucks — we rely on third-party plugins to provide the actual parsing for us. However, it looks like the only Nunjucks plugin that exists (that I could find in a quick search) for Prettier is incomplete, over 4 years old, and very unlikely to support Prettier v3.

Gonna close this as there doesn't appear to be a great solution for this using Prettier currently — sorry :(

If such a plugin is created (or already exists but I missed it) that also supports Prettier v3 I'll take a look at integrating it but until such a time there's not much we could do about this without rolling our own parser which is not something we're prepared to support currently.
