### ISSUE TITLE
tracking-tight order is causing issue

### ISSUE THREAD

**Issue by web-programmer-here** [tailwindlabs/prettier-plugin-tailwindcss#220]
**What version of `prettier-plugin-tailwindcss` are you using?**

` "prettier-plugin-tailwindcss": "0.5.5",`

**What version of Tailwind CSS are you using?**

`"tailwindcss": "3.3.3",`

**What version of Node.js are you using?**

`v18.12.1`

**What package manager are you using?**

`npm`

**What operating system are you using?**

`macOS`

**Describe your issue**

I keep getting this error: 

```
Replace `tracking-tight·flex-auto·text-2xl·font-bold` with `flex-auto·text-2xl·font-bold·tracking-tight`  prettier/prettier
Replace `tracking-tight·flex-auto·text-2xl·font-bold` with `flex-auto·text-2xl·font-bold·tracking-tight`  prettier/prettier
```

only happening with `tracking-tight`. Prettier VSCode auto formats the code by adding tracking-tight in the beginning but I get the other error.

**Comment by web-programmer-here** [comment]
also `tracking-tighter` order works, it is ordered like this: 

```
flex-auto text-2xl font-bold tracking-tighter
```

**Comment by thecrypticace** [comment]
@web-programmer-here Chances are I'd probably have to look at the whole project.

You could, if you wanted, clone this repo, build a non-minified version of the plugin, pack it, and install it into your project so you can add console log statements where do do config loading.

That's basically what I'd end up doing if I didn't happen to notice anything else.

**Comment by MilesWuCode** [comment]
![image](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/1192835/f8e269d8-7218-4b66-a887-42c630fe5a97)

https://github.com/MilesWuCode/nuxt3-demo
path : components/Post/Card.vue

some issues ?

**Comment by thecrypticace** [comment]
@MilesWuCode Nah, that change looks right to me. It's just saying the order of the classes is `card card-compact` and running from the CLI and from VSCode produce the same results.

**Comment by thecrypticace** [comment]
@MilesWuCode Oh hmm it seems to be flip flopping (it was stable for a sec in VSCode but now it's not) which shouldn't be happening. I'll take a look.

**Comment by thecrypticace** [comment]
@web-programmer-here  Hey there's a chance if you have a plugin or a layer that is adding a rule that includes `tracking-tight` alongside another class that it could be the cause. We've just merged a PR to fix that.

Once it is I'll post here and if you could give it a try and see if your issue is fixed? If it's no

@MilesWuCode This was the source of the sorting bug in your project. As above I'll post once the insiders build is available to test.

**The insiders build of Tailwind CSS should be available in about 15–20m.**

Insiders builds can be installed via npm like so:
```
npm install tailwindcss@insiders
```

**Comment by thecrypticace** [comment]
Okay the insiders build is now available:
```
npm install tailwindcss@insiders
```

The version installed should be `0.0.0-insiders.ad66635`.

**Comment by MilesWuCode** [comment]
> Okay the insiders build is now available:
> 
> ```
> npm install tailwindcss@insiders
> ```
> 
> The version installed should be `0.0.0-insiders.ad66635`.

working! thinks.
