### ISSUE TITLE
Error: ENOENT: no such file or directory, can not find path to preflight.css

### ISSUE THREAD

**Issue by DaLukasDev** [tailwindlabs/prettier-plugin-tailwindcss#230]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.5.8

**What version of Tailwind CSS are you using?**

 v3.3.6

**What version of Node.js are you using?**

v20.9.0

**What package manager are you using?**

PNPM

**What operating system are you using?**

Linux

**Reproduction URL**

[Reproduction repo](https://github.com/DaLukasDev/tailwind-sort-repro)

To reproduce:
- `pnpm i` in root of the repo.
- Try to format a file on save in the UI packages or format using the shortcut

Downgrading to 0.5.7 will fix the issue.

**Describe your issue**

The prettier plugin in VSCode throws following error when trying to format a file after upgrading to 0.5.8.

` Error: ENOENT: no such file or directory, open '/home/user/dev/tailwind-sort-repro/node_modules/.pnpm/prettier-plugin-tailwindcss@0.5.8_@ianvs+prettier-plugin-sort-imports@4.1.1_prettier@3.1.0/node_modules/prettier-plugin-tailwindcss/dist/css/preflight.css' `

This does not happen with version 0.5.7.

**Comment by thecrypticace** [comment]
whoops — new patch release incoming

**Comment by thecrypticace** [comment]
Fixed in v0.5.9 — thanks for catching!
