### ISSUE TITLE
plugin doesn't work in VSCode

### ISSUE THREAD

**Issue by Sahasrara** [tailwindlabs/prettier-plugin-tailwindcss#232]
**What version of `prettier-plugin-tailwindcss` are you using?**

0.4.1

**What version of Tailwind CSS are you using?**

3.3.6

**What version of Node.js are you using?**

21.2.0

**What package manager are you using?**

pnpm, npm, and yarn (tried them all)

**What operating system are you using?**

Windows

**Reproduction URL**

https://github.com/Sahasrara/TailwindPluginRepro

**Describe your issue**

The prettier plugin isn't sorting classes. Try changing and saving Tobbar.svelte. The class list won't sort.

**Comment by adamwathan** [comment]
Hey! It looks like you don't have `prettier-plugin-tailwindcss` installed:

https://github.com/Sahasrara/TailwindPluginRepro/blob/main/package.json#L27-L28

After cloning your project, installing the plugin, and restarting VS Code, it is sorting classes for me as expected:

https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/4323180/0d4c3bc5-604d-4be2-af9e-be08a710fc2d

**Comment by Sahasrara** [comment]
My goodness, thanks! I had replicated this repo using the project that wasn't working. Since this works, I decided to go with this and copy over the other project until it stops working.

I'm not sure what's different between the two, but I'm good now.

**Comment by kgnfth** [comment]
@Sahasrara You may change the about text 😂
<img width="1031" alt="image" src="https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/73314940/7fba4056-96f3-483c-8644-111d73aba3cd">

**Comment by devbyray** [comment]
> Hey! It looks like you don't have `prettier-plugin-tailwindcss` installed:
> 
> https://github.com/Sahasrara/TailwindPluginRepro/blob/main/package.json#L27-L28
> 
> After cloning your project, installing the plugin, and restarting VS Code, it is sorting classes for me as expected:
> 
>  Untitled.mov

Restarting Visual Studio Code fixed it for me as well 👍
