### ISSUE TITLE
Plugin not processing .erb files

### ISSUE THREAD

**Issue by Vorkosigan76** [tailwindlabs/prettier-plugin-tailwindcss#233]
**What version of `prettier-plugin-tailwindcss` are you using?**

For example: v0.5.9

**What version of Tailwind CSS are you using?**

For example: v3.3.6

**What version of Node.js are you using?**

For example: v20.6.1

**What package manager are you using?**

For example: npm, Yarn

**What operating system are you using?**

For example: WSL with Ubuntu on Windows 11

**Describe your issue**

I am using TailwindCSS on Ruby on Rails and wanted to use this plugin to reorder classes. Nothing happens

When running prettier in command line in debug, I get the following
resolve config from '/xxxxxx/app/views/devise/unlocks/new.html.erb'
[debug] loaded options `{"trailingComma":"none","tabWidth":2,"useTabs":false,"insertPragma":true,"plugins":["@prettier/plugin-ruby","prettier-plugin-tailwindcss"],"tailwindConfig":"./tailwind.config.js"}`
[debug] applied config-precedence (cli-override): {"trailingComma":"none","tailwindConfig":"./tailwind.config.js","insertPragma":true,"plugins":["@prettier/plugin-ruby","prettier-plugin-tailwindcss"],"tabWidth":2,"useTabs":false}

My .prettierrc.json
{
  "trailingComma": "none",
  "tabWidth": 2,
  "useTabs": false,
  "insertPragma": true,
  "plugins": ["@prettier/plugin-ruby", "prettier-plugin-tailwindcss"],
  "tailwindConfig": "./tailwind.config.js"
}

My tailwind.conf.js
module.exports = {
  content: [
    "./app/components/**/*.html.erb",
    "./app/views/**/*.html.erb",
    "./app/views/**/*.turbostream.erb",
    "./app/helpers/**/*.rb",
    "./app/javascript/**/*.js",
    "./app/javascript/**/*.tsx",
    "./app/javascript/**/*.ts"
  ],
  plugins: [
    require("@tailwindcss/forms")
    // ...
  ]
};

**Comment by thecrypticace** [comment]
Hey, this is because we don't have support for Ruby. I'll look into this though to see if it's feasible.

**Comment by thecrypticace** [comment]
Hey, so we generally rely on existing plugins to help provide support for languages. I did some looking around and while `@prettier/plugin-ruby` is a thing it doesn't format ERB files. There is an older ERB plugin called `prettier-plugin-erb` but it unfortunately does not support Prettier v3.

If that plugin gets updated (or another plugin replaces it) we can look into what would be required to support ERB. But since it doesn't we're not going to add support for formatting / sorting in ERB files right now. Sorry we don't have better news.

**Comment by kdiogenes** [comment]
I recently started using this plugin for ERB support and it's working very well: https://github.com/ForAzens/prettier-plugin-html-erb

**Comment by thecrypticace** [comment]
Ah thanks for the note! I'll take a look at that soon

**Comment by jondkinney** [comment]
@thecrypticace any progress on this one? I'd love to be able to get tailwind css class sorting working with erb!

**Comment by drale2k** [comment]
Would love to see this happen and send over $100 to support the hours required at least a little bit

**Comment by tagliala** [comment]
Hello,

the official [prettier-ruby](https://github.com/prettier/plugin-ruby) plugin appears to support `.haml` syntax. Is there by any way the possibility to consider to implement this feature for haml files?

**Comment by thecrypticace** [comment]
@tagliala unfortunately that plugin only passes strings to/from an ruby internal server that does the actual formatting so there's no real AST for us to modify.
