### ISSUE TITLE
Getting prettier error while linting with TW 3.4

### ISSUE THREAD

**Issue by bigint** [tailwindlabs/prettier-plugin-tailwindcss#236]
**What version of `prettier-plugin-tailwindcss` are you using?**

For example: v0.5.9

**What version of Tailwind CSS are you using?**

For example: v3.4

**What version of Node.js are you using?**

For example: v18.0.0

**What package manager are you using?**

For example: pnpm

**What operating system are you using?**

For example: macOS, Windows

**Reproduction URL**

https://github.com/heyxyz/hey

**Describe your issue**

<img width="1738" alt="image" src="https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/69431456/7dd7c895-c919-4c89-8b2e-e5faa97e6568">

**Comment by bigint** [comment]
Here is the PR https://github.com/heyxyz/hey/pull/4290

**Comment by thecrypticace** [comment]
Hey, this is expected. We changed the order of some stuff and that's going to move dark classes toward the end where they weren't before.

**Comment by bigint** [comment]
@thecrypticace but its also happening for the new `size-*` classnames, is it expected? any ideas how to fix the lint errors? we changed nothing from our size, we just added replaced with h and w with size classes 🙇🏼

**Comment by thecrypticace** [comment]
@bigint The size classes didn't exist before 3.4 — I'm guessing you had some custom ones that you removed? In that case, yes it's expected. Our own classes will appear before any introduced by plugins.

**Comment by thecrypticace** [comment]
The fix for the lint errors is to run prettier again and commit the changes.

**Comment by bigint** [comment]
But seems like the package version has not been bumped!

<img width="1358" alt="Screenshot 2023-12-21 at 9 43 59 PM" src="https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/69431456/817229ce-61e8-4002-8089-d84ea08471c2">

I think there is still conflict between eslint-prettier and prettier

prettier works fine, but while running with eslint-prettier it throws the error!

prettier:fix didn't helped @thecrypticace 🙇🏼

**Comment by bigint** [comment]
<img width="233" alt="Screenshot 2023-12-21 at 9 45 05 PM" src="https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/69431456/dd864889-7a36-4b4e-99e4-ac8bd31bbeda">

**Comment by thecrypticace** [comment]
There was no change in the prettier plugin — nor was any change necessary. The new sorting is a result of upgrading Tailwind CSS which the prettier plugin has picked up properly.

Do you have a link to your project?

**Comment by bigint** [comment]
https://github.com/heyxyz/hey

**Comment by bigint** [comment]
Here is the PR https://github.com/heyxyz/hey/pull/4290

**Comment by sasicodes** [comment]
+1 

we are experiencing the same. https://github.com/tapexyz/tape

**Comment by bigint** [comment]
For the time being, i just commented the plugin in prettier and pushed!

**Comment by dotoleeoak** [comment]
Hi. I'm facing the same issue, and it seems the issue is resolved with PR #235. The only thing I want is the fixed version to be released. There has been no release after the PR.

**Comment by web-programmer-here** [comment]
@thecrypticace I am also having this issue, is the solution to wait for a new release?

**Comment by thecrypticace** [comment]
@dotoleeoak ah so you're using the prettier plugin without a base tailwind install (CDN and the like). Meant to get a release out but then the holidays hit.

I've got some downtime today — I'll tag a new release!

**Comment by thecrypticace** [comment]
https://github.com/tailwindlabs/prettier-plugin-tailwindcss/releases/tag/v0.5.10

Published and it looks to be available on NPM already.

Ping me if you have any other problems.

**Comment by web-programmer-here** [comment]
@thecrypticace thanks, the issue is fixed

**Comment by dotoleeoak** [comment]
@thecrypticace Thanks! I also confirmed the issue has been fixed.
