### ISSUE TITLE
Inconsistent sorting between formatting all files and a single file

### ISSUE THREAD

**Issue by lesha1201** [tailwindlabs/prettier-plugin-tailwindcss#246]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.5.11

**What version of Tailwind CSS are you using?**

v3.4.1

**What version of Node.js are you using?**

v20.10.0

**What package manager are you using?**

npm, pnpm

**What operating system are you using?**

Windows (WSL)

**Reproduction URL**

https://github.com/lesha1201/tailwind-prettier-plugin-inconsistent-sorting-issue

**Describe your issue**

https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/10157660/8590929d-0f29-4c0c-8752-a2be1496bd5a

`prettier-plugin-tailwindcss` formats a certain file differently when you format all files and only that file. In the reproduction example, there are two components: `ButtonSocialApple` and `ButtonSocialFacebook` which have similar tailwind classes.

```tsx
// src/app/button-social/button-social.apple.tsx
// ...
export function ButtonSocialApple({ children }: ButtonSocialAppleProps) {
  return (
    <div className="[--dr-social-button-color-bg-brand:#000] [--dr-social-button-color-bg-brand_hover:#000] [--dr-social-button-color-fg_on-brand:#fff]">
      {children}
    </div>
  );
}

// src/app/button-social/button-social.apple.tsx
// ...
export function ButtonSocialFacebook({ children }: ButtonSocialFacebookProps) {
  return (
    <div className="[--dr-social-button-color-bg-brand:#1877F2] [--dr-social-button-color-bg-brand_hover:#0C63D4] [--dr-social-button-color-fg_on-brand:#fff]">
      {children}
    </div>
  );
}
```

When you format all files by running:

```sh
npx prettier --write .
```

It produces one result for `ButtonSocialFacebook`:

```tsx
export function ButtonSocialFacebook({ children }: ButtonSocialFacebookProps) {
  return (
    <div className="[--dr-social-button-color-fg_on-brand:#fff] [--dr-social-button-color-bg-brand:#1877F2] [--dr-social-button-color-bg-brand_hover:#0C63D4]">
      {children}
    </div>
  );
}
```

When you format only `ButtonSocialFacebook`:

```sh
npx prettier --write ./src/app/button-social/button-social-facebook.tsx
```

It produces a different result:

```tsx
export function ButtonSocialFacebook({ children }: ButtonSocialFacebookProps) {
  return (
    <div className="[--dr-social-button-color-bg-brand:#1877F2] [--dr-social-button-color-bg-brand_hover:#0C63D4] [--dr-social-button-color-fg_on-brand:#fff]">
      {children}
    </div>
  );
}
```

However, when you remove `ButtonSocialApple` component, it formats `ButtonSocialFacebook` consistently.

**Comment by lesha1201** [comment]
If I remove [`env.context.getClassOrder`](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/blob/1fa24c2d33f17c9729e3f4a2018518a55699969d/src/sorting.js#L86) from `sortClassList` then it works fine so I guess the issue is in `env.context.getClassOrder`.

```js
export function sortClassList(classList, { env }) {
  let classNamesWithOrder = env.context.getClassOrder
    ? env.context.getClassOrder(classList)
    : getClassOrderPolyfill(classList, { env })

  return classNamesWithOrder
    .sort(([, a], [, z]) => {
      if (a === z) return 0
      // if (a === null) return options.unknownClassPosition === 'start' ? -1 : 1
      // if (z === null) return options.unknownClassPosition === 'start' ? 1 : -1
      if (a === null) return -1
      if (z === null) return 1
      return bigSign(a - z)
    })
    .map(([className]) => className)
}
```

**Comment by thecrypticace** [comment]
Hey — so this is a problem in Tailwind CSS itself coupled with the fact that we have to do some things in the Prettier plugin for performance reasons.

I've merged in a fix in https://github.com/tailwindlabs/tailwindcss/pull/12911 and I'm going to work on back porting to v3.4 and get a patch release out this week.

Thanks for pointing this out!
