### ISSUE TITLE
Bad sorting for 'dark:' pseudoselector

### ISSUE THREAD

**Issue by PatrykKuniczak** [tailwindlabs/prettier-plugin-tailwindcss#247]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.5.11

**What version of Tailwind CSS are you using?**

v3.4.1

**What version of Node.js are you using?**

v20.9.0

**What package manager are you using?**

npm

**What operating system are you using?**

Windows 11

**Describe your issue**

The 'dark:' pseudoselector aren't sort properly, cause the part of this properties are localized at the start and rest at the end.

```ts
className={'dark:via-inactive dark:to-inactive relative mt-5 h-1 dark:bg-gradient-to-r dark:from-active dark:via-[30%]'}
```

**Comment by adamwathan** [comment]
Looks like the `via-inactive` and `to-inactive` classes don’t exist so they are getting sorted to the front. Can you share a reproduction?

**Comment by PatrykKuniczak** [comment]
> Looks like the `via-inactive` and `to-inactive` classes don’t exist so they are getting sorted to the front. Can you share a reproduction?

OK, you're right, i incorrectly read 1 article, about styling slider on range input, there's wrong info about 'dark:' pseuodoselector, indeed i don't have this property for the dark mode. Thanks for quick response :)
