### ISSUE TITLE
Please add support for `zackad/prettier-plugin-twig-melody`

### ISSUE THREAD

**Issue by alessandro-newzoo** [tailwindlabs/prettier-plugin-tailwindcss#254]
Hello,

The plugin [trivago/prettier-plugin-twig-melody ](https://github.com/trivago/prettier-plugin-twig-melody) was abandoned a long time ago and therefore it does not support Prettier 3.x _(This plugin used to be supported by older versions of `prettier-plugin-tailwindcss`)_.

**BUT**, this awesome person - god bless them - forked it, and made it work with Prettier v3: [zackad/prettier-plugin-twig-melody](https://github.com/zackad/prettier-plugin-twig-melody)

If it's not too much work, could you guys please add support for it? I know it's small and has no stars yet, but it works perfectly with v3, and I can guarantee you it's the only Prettier plugin on the internet working with v3 at the moment.

I'm currently stuck with Prettier 2.x and `prettier-plugin-tailwindcss` `v0.4.1`, so this would really help me (and other people working with Twig + TailwindCSS) tremendously.

Thank you,
Alessandro

**Comment by thecrypticace** [comment]
Oh sweet — I'll take a look in a few!

**Comment by thecrypticace** [comment]
Ah they haven't published a separate package and are relying on GitHub url versioning. I think it'd probably best to wait until they publish this as a scoped package. I'll keep an eye on it though to see if that happens.

**Comment by thecrypticace** [comment]
Gonna close for now but will absolutely take a look once they do

**Comment by alessandro-newzoo** [comment]
hey @thecrypticace thanks for picking this up, I've asked the author of the fork if they can do that, I'll keep you posted!

**Comment by zackad** [comment]
Other than publishing as npm package, what do i need to make my fork to be compatible with `prettier-plugin-tailwindcss`? Do I need to convert my fork into ES module or it's not a requirement?

**Comment by thecrypticace** [comment]
> Other than publishing as npm package, what do i need to make my fork to be compatible with `prettier-plugin-tailwindcss`? Do I need to convert my fork into ES module or it's not a requirement?

Nah, your fork works almost as is. We don't currently support plugins that simultaneously support Prettier 2 _and_ 3 but it's an easy thing to support. (the signature for `parse()` changed in v3 so that options is the 2nd argument not 3rd).

**Comment by thecrypticace** [comment]
I've re-added support and will get a release out today!

**Comment by alessandro-newzoo** [comment]
bless you both, thank you so much!

**Comment by alessandro-newzoo** [comment]
@thecrypticace sorry to necro this but I think it's good that you have some context. Let me know if you'd rather I opened a new issue.

@zackad just updated the package and renamed it from `@zackad/prettier-plugin-twig-melody` to `@zackad/prettier-plugin-twig` - could you pretty please update the plugin to support the new package name? 🙏🏻

https://www.npmjs.com/package/@zackad/prettier-plugin-twig

Thank you!

**Comment by thecrypticace** [comment]
Ah okay cool — will do. I opened a separate issue for me so I don't forget. I probably won't get to it until this evening though.

**Comment by alessandro-newzoo** [comment]
No rush at all, take your time man! Thank you.

**Comment by bitbirddev** [comment]
Hi @alessandro-newzoo, any updates on this?

**Comment by ttskch** [comment]
@alessandro-newzoo @bitbirddev Please take a look at this: https://github.com/ttskch/prettier-plugin-tailwindcss-anywhere

**Comment by alessandro-newzoo** [comment]
> @alessandro-newzoo @bitbirddev Please take a look at this: https://github.com/ttskch/prettier-plugin-tailwindcss-anywhere

Hi Takashi and thanks for this, very interesting!
I'm not sure I'll need it as I'm already using https://www.npmjs.com/package/@zackad/prettier-plugin-twig for formatting my twig files, and that works well with the `prettier-plugin-tailwindcss` plugin, but definitely good to have for those who need it ♥️

**Comment by bitbirddev** [comment]
@alessandro-newzoo are you using an oder version of @zackad/prettier-plugin-twig(-melody)?

**Comment by alessandro-newzoo** [comment]
@bitbirddev yeah sorry for the confusion, I just realized.

I'm currently using [@zackad/prettier-plugin-twig-melody@0.6.0](https://www.npmjs.com/package/@zackad/prettier-plugin-twig-melody) _(a)_, which is the last version before it was renamed to [@zackad/prettier-plugin-twig](https://www.npmjs.com/package/@zackad/prettier-plugin-twig) _(b)_.

_(a)_ is compatible with `prettier-plugin-tailwindcss@0.6.8`, but I'd really like to switch to _(b)_ (the renamed and latest version of `prettier-plugin-twig`). This switch, however, requires Tailwind Labs to merge your PR so that `prettier-plugin-tailwindcss` can support _(b)_ as well.

### **To clarify:**
The plugin originally known as https://www.npmjs.com/package/@zackad/prettier-plugin-twig-melody _(a)_ has been renamed to https://www.npmjs.com/package/@zackad/prettier-plugin-twig _(b)_.
For `prettier-plugin-tailwindcss` to work with _(b)_, Tailwind Labs needs to update their supported plugins list to reflect the new name.

**Currently:**
- _(a)_ works with `prettier-plugin-tailwindcss`
- _(b)_ does **not** work with `prettier-plugin-tailwindcss` until Tailwind Labs updates their supported plugins list

**Comment by alessandro-newzoo** [comment]
@bitbirddev haha yeah, it's been a very long, confusing and frustrating journey, but thanks to zackad and your PR, hopefully this will be the end of it (assuming they'll ever merge it 😅)
Thanks!

**Comment by bitbirddev** [comment]
you can already use it if you want to. in your project directory run

```
bun add github:bitbirddev/prettier-plugin-tailwindcss
# yarn add https://github.com/bitbirddev/prettier-plugin-tailwindcss
# npm i https://github.com/bitbirddev/prettier-plugin-tailwindcss

cd node_modules/prettier-plugin-tailwindcss
npm install
npm run prebuild && npm run build && npm run postbuild
```

**Comment by alessandro-newzoo** [comment]
Thank you! I'd rather wait as I have a very complicated setup and I'd rather stick to live packages if possible, but I'll keep this in mind should tailwindlabs decide to never merge your PR 🤞🏻
