### ISSUE TITLE
Doesn't work with Shopify Liquid extension

### ISSUE THREAD

**Issue by stijns96** [tailwindlabs/prettier-plugin-tailwindcss#259]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.5.12

**What version of Tailwind CSS are you using?**

v3.4.1

**What version of Node.js are you using?**

v20.10.0

**What package manager are you using?**

For example: pnpm/npm

**What operating system are you using?**

macOS

**Describe your issue**

Previously we used the @shopify/prettier-plugin-liquid plugin to format our liquid code, but nowadays the Shopify Liquid extension is formatting liquid as well. Somehow this will break prettier-plugin-tailwindcss.

I also opened an [issue](https://github.com/Shopify/theme-tools/issues/342) on the repo of the Shopify Liquid extension.

**Comment by thecrypticace** [comment]
Hey, this is an issue with their extension. They [explicitly call Prettier with a single plugin](https://github.com/Shopify/theme-tools/blob/b27b698f0265b3726bed2f1e2f1cadcabf5b9192/packages/vscode-extension/src/formatter.ts#L47-L57). I thought Prettier's overrides feature could be a workaround but that doesn't seem to work unfortunately. I'd suggest, for the time being, changing the default formatter for Liquid files to Prettier instead by adding this to your VSCode config:

```json
"[liquid]": {
  "editor.defaultFormatter": "esbenp.prettier-vscode"
}
```

If you do this it should start working again as long as you have both plugins and installed and specified in your Prettier config.

Closing as this isn't an issue on our end.

**Comment by stijns96** [comment]
Hi @thecrypticace,

Thanks for answering. I already thought so... I opened an issue there as well.
