### ISSUE TITLE
Not working with `prettier-plugin-organize-imports`

### ISSUE THREAD

**Issue by jacobwgillespie** [tailwindlabs/prettier-plugin-tailwindcss#26]
It appears that either `prettier-plugin-tailwindcss` or `prettier-plugin-organize-imports` affect the file, based on which one appears last in the config plugin list, but not both.

**Prettier Version:** 2.5.1
**`prettier-plugin-tailwindcss` version:** 0.1.4
**`prettier-plugin-organize-imports` version:** 2.3.4

I am currently able to somewhat merge the two plugins manually by using the `preprocess` function from `prettier-plugin-organize-imports`, but it would be nice if the two got along without the patch:

```js
// merged-prettier-plugin.js

const tailwind = require('prettier-plugin-tailwindcss')
const organizeImports = require('prettier-plugin-organize-imports')

const combinedFormatter = {
  ...tailwind,
  parsers: {
    ...tailwind.parsers,
    ...Object.keys(organizeImports.parsers).reduce((acc, key) => {
      acc[key] = {
        ...tailwind.parsers[key],
        preprocess(code, options) {
          return organizeImports.parsers[key].preprocess(code, options)
        },
      }
      return acc
    }, {}),
  },
}

module.exports = combinedFormatter
```

```js
// .prettierrc.js

module.exports = {
  plugins: [require('./merged-prettier-plugin.js')],
  ...
}
```

**Comment by joshmedeski** [comment]
I have the same issue. I'm going to wait until this has been resolved to use the tailwind plugin.

**Comment by reinink** [comment]
Hey! Thanks for reporting this. I've created a new issue (#31) dedicated to keeping track of Prettier plugins that are not compatible with this plugin. Closing this issue in favor of that 👍

Please feel free to post this incompatibility with `prettier-plugin-organize-imports ` in that issue, it would be great to have it there for quick reference.

**Comment by reinink** [comment]
Update on this one — we've added support for this plugin in the latest (beta) version of our Prettier plugin. You can read more about that here: https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/31#issuecomment-1312202554
