### ISSUE TITLE
Sorting of extended values does not work properly

### ISSUE THREAD

**Issue by dmitrystas** [tailwindlabs/prettier-plugin-tailwindcss#262]
**What version of `prettier-plugin-tailwindcss` are you using?**

Latest

**What version of Tailwind CSS are you using?**

Latest

**What version of Node.js are you using?**

Latest

**What package manager are you using?**

pnpm

**What operating system are you using?**

Ubuntu

**Describe your issue**

Sorting of some (I've found spacing and fontSize, but maybe there are some others) extended values is broken. For example, here is the result of standard 14 spacing sorting:

`class="fixed flex p-14"`

Looks good. But if we try to sort some non-standard value, like

```
export default {
  extend: {
    spacing: {
      15: '3.75rem'
    }
  }
}
```

we get

`class="p-15 fixed flex"`

i.e. p-15 is at the beginning.

At first I thought this was true for all non-standard values. But this is not the case, for example, sorting of z-index
```
export default {
  extend: {
    zIndex: {
      1: '1'
    }
  }
}
```

works correctly and after sorting z-1 is not at the beginning

`class="fixed z-1 flex"`

**Comment by adamwathan** [comment]
Weird one! Here's a minimal reproduction for when we get a chance to look into this:

https://play.tailwindcss.com/1CAwzxiiNJ

**Comment by dmitrystas** [comment]
Hmm, it looks like the incorrect behavior is only true for VSCode... In the console
`prettier --write ...`
works pretty good...

**Comment by thecrypticace** [comment]
> Weird one! Here's a minimal reproduction for when we get a chance to look into this:
> 
> https://play.tailwindcss.com/1CAwzxiiNJ

If you hit tidy or cmd-s it sorts correctly.

**Comment by dmitrystas** [comment]
Jordan, I'm really sorry that you wasted your time on me :( I've updated all my project/VSCode dependencies to the latest versions, and now both VSCode sorting as well as CLI sorting work perfect. I apologize again and thank you!

**Comment by thecrypticace** [comment]
@dmitrystas No worries at all! And hey, we ended up finding (and fixing) a bug in Play because of it. Though the fix isn't live yet — got a few other things we're working on.
