### ISSUE TITLE
Plugin integration with the third-party imports plugin is not working

### ISSUE THREAD

**Issue by nkwwk** [tailwindlabs/prettier-plugin-tailwindcss#266]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.5.14

**What version of Tailwind CSS are you using?**

v3.4.3

**What version of Node.js are you using?**

v20.10.0

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Describe your issue**

I have followed the README.md and tried to set up the project using the following config. Still, it's not working with either `prettier-plugin-organize-imports`, `@ianvs/prettier-plugin-sort-imports`, or `@trivago/prettier-plugin-sort-imports`.

.prettierrc.json
```json
{
  "trailingComma": "es5",
  "semi": true,
  "tabWidth": 2,
  "singleQuote": true,
  "jsxSingleQuote": false,
  "printWidth": 100,
  "plugins": ["prettier-plugin-organize-imports", "prettier-plugin-tailwindcss"],
  "importOrder": ["^[./]", "^@/(.*)$"],
  "importOrderSeparation": true,
  "importOrderSortSpecifiers": true
}
```

However, `prettier-plugin-organize-imports` and the plugin works when the loading order is reversed.

Notes: `importOrder` related attributes do not affect the below situation.

.prettierrc.json
```json
{
  "trailingComma": "es5",
  "semi": true,
  "tabWidth": 2,
  "singleQuote": true,
  "jsxSingleQuote": false,
  "printWidth": 100,
  "plugins": ["prettier-plugin-tailwindcss", "prettier-plugin-organize-imports"]
}
```

I am using the VS Code format on save feature with esbenp.prettier-vscode to trigger the formatting.

**Comment by thecrypticace** [comment]
Hi! A few things here:
1. Our plugin must **always** be listed last per the readme on plugin integration.
2. The `importOrder*` attributes are options that come from a different plugin (`@trivago/prettier-plugin-sort-imports`) so those will not do anything for `prettier-plugin-organize-imports`
3. I set up a small Vite project with Tailwind v3, prettier, and both plugins, and everything is sorting as expected.

Can you provide an example project that doesn't work?

**Comment by nkwwk** [comment]
I created a new project to test the integration, which works fine with the configuration. Besides, I installed the sorting plugin and listed it last, then closed the VS project and restarted it. Everything works fine now.

**Comment by thecrypticace** [comment]
Okay cool — glad you got it working 👍
