### ISSUE TITLE
width and height sorting order

### ISSUE THREAD

**Issue by bourhaouta** [tailwindlabs/prettier-plugin-tailwindcss#27]
Hello,

Just checking if there's a reason behind why sorting width and height goes like this: `h-... w-...` instead of the width before height

**Comment by adamwathan** [comment]
Hey! No real reason, just had to pick one 👍

**Comment by 7iomka** [comment]
> Hey! No real reason, just had to pick one 👍

and why did you choose a counterintuitive?
for example svg elements has viewbox values: first is width, second is height, and the same as it attributes.
But when I'm looking on my sorted classes each time I have an extreme dislike for this reverse order.
And there's no way to adjust it.
