### ISSUE TITLE
bug: formatting lost with the new version of the plugin

### ISSUE THREAD

**Issue by ovflowd** [tailwindlabs/prettier-plugin-tailwindcss#280]
**What version of `prettier-plugin-tailwindcss` are you using?**

0.6.1

**What version of Tailwind CSS are you using?**

3.4.3

**What version of Node.js are you using?**

v20.11.1

**What package manager are you using?**

NPM

**What operating system are you using?**

Windows 11

**Reproduction URL**

https://github.com/nodejs/nodejs.org/pull/6803 (Specifically: https://github.com/nodejs/nodejs.org/tree/583b5ca191e1e8f478f9a3d31affefcbe365339c)

**Describe your issue**

Upgrading the prettier plugin from 0.5.14 to 0.6.1 causes prettier to force all class names to be within the same line.

On our project, we intentionally separated each Tailwind token per line to improve readability, and this was working fine, and the plugin was still nicely sorting the tokens and removing duplicates. But now, it is breaking the formatting.

![image](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/12037269/030aadc9-124d-4c63-8704-87c54b604f76)

I didn't see this mentioned anywhere within the changelog so I assume it is a bug

**Comment by thecrypticace** [comment]
As of v0.6.0 our plugin now removes whitespace around classes by default — this includes new lines — but there is an option to disable it. Add the following to your prettier config (whether that be in `.prettierrc`, `prettier.config.js`, `package.json`, etc…):
```json
{
  "tailwindPreserveWhitespace": true
}
```

And it is in the change log :)
> Remove extra whitespace around classes (https://github.com/tailwindlabs/prettier-plugin-tailwindcss/pull/272)

Hope that helps! ✨

**Comment by ovflowd** [comment]
I saw that entry on the changelog but did not connect the dots. That's awesome, thanks for the quick reply :)
