### ISSUE TITLE
Whitespace removal in class attribute breaks this

### ISSUE THREAD

**Issue by pkyeck** [tailwindlabs/prettier-plugin-tailwindcss#283]
**What version of `prettier-plugin-tailwindcss` are you using?**

I updated from prettier-plugin-tailwindcss  0.5.14  →  0.6.1

**What version of Tailwind CSS are you using?**

3.4.3

**What version of Node.js are you using?**

20.14.1

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Describe your issue**

My problem wasn't happening before but since I updated to 0.6.1 prettier wants to replace this

```diff
diff --git a/Comment.ts b/Comment.ts
--- a/Comment.ts
+++ b/Comment.ts
@@ -73,5 +73,5 @@
             <ul
               data-${CO_EXTRA_OPTIONS}
-              class="before:content-[' '] before:border-t-0 after:content-[' '] after:border-t-0 absolute -right-2 top-2 z-30 rounded-m border-s border-gray-1-dark bg-white  p-1 shadow-xl before:absolute before:right-[10px] before:top-[-13px] before:z-[1]  before:ml-[-6px] before:block before:h-[6px] before:w-[6px] before:overflow-hidden before:border-[6px] before:border-solid before:border-transparent before:border-b-gray-1-dark after:absolute after:right-[10px] after:top-[-12px] after:z-[2] after:ml-[-6px] after:block after:h-[6px] after:w-[6px] after:overflow-hidden after:border-[6px] after:border-solid  after:border-transparent after:border-b-white"
+              class="before:content-[' '] before:border-t-0 after:content-[' after:border-t-0 absolute -right-2 top-2 z-30 rounded-m border-s border-gray-1-dark bg-white  p-1 shadow-xl before:absolute before:right-[10px] before:top-[-13px] before:z-[1]  before:ml-[-6px] before:block before:h-[6px] before:w-[6px] before:overflow-hidden before:border-[6px] before:border-solid before:border-transparent before:border-b-gray-1-dark after:absolute after:right-[10px] after:top-[-12px] after:z-[2] after:ml-[-6px] after:block after:h-[6px] after:w-[6px] after:overflow-hidden after:border-[6px] after:border-solid  after:border-transparent after:border-b-white"
             >
               ${html.each(
```

so this `before:content-[' '] before:border-t-0 after:content-[' '] after:border-t-0 absolute`  
becomes this `before:content-[' '] before:border-t-0 after:content-[' after:border-t-0 absolute`

even though I added the `tailwindPreserveWhitespace: true`.

Maybe you have an idea what the culprit could be ... otherwise I'll have to wait with the update

**Comment by thecrypticace** [comment]
This is happening because of duplicate class removal — not whitespace removal. We're seeing `']` as a duplicate class. Classes are never allowed to contain spaces in HTML or CSS so the classes `before:content-[' ']` and `after:content-[' ']` are not valid classes (Tailwind or otherwise). You want this instead: `before:content-['_']` and `after:content-['_']`.

**Comment by pkyeck** [comment]
thanks a lot for the quick reply - even though this wasn't my code (I was just the dev who saw the removal), I learned something today!!
