### ISSUE TITLE
Escaping slashes are stripped

### ISSUE THREAD

**Issue by hugovandevliert** [tailwindlabs/prettier-plugin-tailwindcss#284]
**What version of `prettier-plugin-tailwindcss` are you using?**

0.5.3

**What version of Tailwind CSS are you using?**

3.1.7

**What version of Node.js are you using?**

18.7.0

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/hugovandevliert/prettier-plugin-tailwindcss-escaping-slashes

Steps: 

1. `npm i` 
2.  `npx prettier --write foo.tsx`
3. `git diff`

Note: this reproduction repo uses different versions as those listed above.

**Describe your issue**

Escaping slashes in tailwind classes are stripped when used in combination with [classNames](https://github.com/JedWatson/classnames).

Original code:

```tsx
export default () => (
  <span
    className={classNames('md:p-2 m-1 m-3 p-4', "before:content-['\\ea53']")}
  />
);
```

After running `npx prettier --write file_name.tsx`:

```tsx
export default () => (
  <span
    className={classNames('m-1 m-3 p-4 md:p-2', "before:content-['ea53']")}
  />
);
```

Note the missing `\\`.

**Comment by thecrypticace** [comment]
I've merged a fix for this and will try to get a patch out later today 👍

**Comment by hugovandevliert** [comment]
That's impressively quick. Thanks!
