### ISSUE TITLE
Incompatibility with other Prettier plugins

### ISSUE THREAD

**Issue by reinink** [tailwindlabs/prettier-plugin-tailwindcss#31]
To make this plugin work we had to use private Prettier APIs that can only be used by a single plugin at once. This means this plugin is incompatible with other Prettier plugins that are using the same APIs.

This GitHub issue will serve as a place to keep track of which Prettier plugins are incompatible — and hopefully we'll eventually find some workarounds, or even a proper long term solution. 👍

## Known incompatibilities

- `@trivago/prettier-plugin-sort-imports`
- `prettier-plugin-organize-imports`
- `prettier-plugin-svelte` *(see below)*
- `prettier-plugin-twig-melody`

## prettier-plugin-svelte

We've bundled the `prettier-plugin-svelte` directly into `prettier-plugin-tailwindcss`, so if you'd like to use this plugin with Svelte, just uninstall `prettier-plugin-svelte` and everything should work as expected.

## Workarounds

While I have not tested it yet, @Mattinton provided one possible workaround in [this comment](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/9#issuecomment-1021028722).

**Comment by jacobwgillespie** [comment]
I originally opened issue #26 about `prettier-plugin-organize-imports` - in that specific case, I'm able to work around the incompatibility for now by monkey-patching `prettier-plugin-tailwindcss` so that each overlapping parser uses the `preprocess` function from `prettier-plugin-organize-imports`, like so:

```js
// merged-prettier-plugin.js

const tailwind = require('prettier-plugin-tailwindcss')
const organizeImports = require('prettier-plugin-organize-imports')

const combinedFormatter = {
  ...tailwind,
  parsers: {
    ...tailwind.parsers,
    ...Object.keys(organizeImports.parsers).reduce((acc, key) => {
      acc[key] = {
        ...tailwind.parsers[key],
        preprocess(code, options) {
          return organizeImports.parsers[key].preprocess(code, options)
        },
      }
      return acc
    }, {}),
  },
}

module.exports = combinedFormatter
```

```js
// .prettierrc.js

module.exports = {
  plugins: [require('./merged-prettier-plugin.js')],
  ...
}
```

This works for now because, from what I can tell, `prettier-plugin-tailwindcss` doesn't set a preprocessor, and `prettier-plugin-organize-imports` does all of its work in the preprocessor.

Looking forward to whatever eventual fix removes the need for the patch!

**Comment by qortex** [comment]
From my experience, https://github.com/francoismassart/eslint-plugin-tailwindcss can be added to the list of incompabilities.

**Comment by ianjamieson** [comment]
Might be a bit of an edge case. But I am using Laravel and subsequently Blade template files. 

So that prettier runs on these files I am using [@shufo/prettier-plugin-blade](https://github.com/shufo/prettier-plugin-blade). But as this issue suggests, Tailwind classes are not sorted when run with this plugin.

**Comment by rwwagner90** [comment]
Seems this one might be incompatible as well https://github.com/withastro/prettier-plugin-astro

**Comment by dacodekid** [comment]
@rwwagner90  It's not that this plugin is incompatible with `prettier-plugin-astro`, but this plugin only works with a few extensions (such as `vue`, `html`, etc).

**Comment by darylknight** [comment]
Subscribing to this. Working with Craft CMS, it's disappointing to see this is incompatible with prettier-plugin-twig-melody.

**Comment by rwwagner90** [comment]
> @rwwagner90 It's not that this plugin is incompatible with `prettier-plugin-astro`, but this plugin only works with a few extensions (such as `vue`, `html`, etc).

Would it be possible to add astro support?

**Comment by jlarmstrongiv** [comment]
Does anyone have an example repo with `prettier-plugin-tailwindcss` and `@trivago/prettier-plugin-sort-imports`?  I couldn’t get them to work together.

**Comment by doubled3264** [comment]
plugin not work when i use @apply on .scss file ? :(

**Comment by JamesIves** [comment]
Seem to be having problems when parsing Angular HTML files too

**Comment by nunocasteleira** [comment]
I don't know if it is also related to this, but I can't have `prettier-plugin-tailwindcss` working alongside `@tailwindcss/forms`. It says it doesn't find it.

**Comment by joshmedeski** [comment]
@nunocasteleira this issue is related to prettier plugins conflicting with each other.

If your system can't find `@tailwindcss/forms` try reinstalling it with `npm install @tailwindcss/forms`.

If you continue to have problems open an issue on the [forms repo](https://github.com/tailwindlabs/tailwindcss-forms).

**Comment by nunocasteleira** [comment]
> If your system can't find `@tailwindcss/forms` try reinstalling it with `npm install @tailwindcss/forms`.

Yes, but the problem arises when  `prettier-plugin-tailwindcss` is installed. If I uninstall it, I'm able to run prettier (with @tailwind/forms also installed), whereas it fails with prettier plugin tailwindcss added to my package.json.

**Comment by christiaansnoei** [comment]
> Might be a bit of an edge case. But I am using Laravel and subsequently Blade template files.
> 
> So that prettier runs on these files I am using [@shufo/prettier-plugin-blade](https://github.com/shufo/prettier-plugin-blade). But as this issue suggests, Tailwind classes are not sorted when run with this plugin.

Did you find a way to get this working?

**Comment by nunocasteleira** [comment]
@joshmedeski I have a very minimal prettierrc:
```
{
  "arrowParens": "always",
  "bracketSameLine": true,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "semi": true,
  "singleQuote": false,
  "trailingComma": "all"
}
```

**Comment by joshmedeski** [comment]
@nunocasteleira I'm stumped. I don't know why `@tailwindcss/forms` has any relationship with `prettier-plugin-tailwindcss`.

**Comment by nunocasteleira** [comment]
I can share the repo if you want.

**Comment by scott-lc** [comment]
Also appears to be incompatible with [prettier-plugin-jsdoc](https://www.npmjs.com/package/prettier-plugin-jsdoc).

My prettier config:
```
{
  "$schema": "http://json.schemastore.org/prettierrc",
  "endOfLine": "lf",
  "jsxSingleQuote": true,
  "printWidth": 100,
  "quoteProps": "consistent",
  "singleQuote": true,
  "trailingComma": "none",
  "useTabs": false,

  "overrides": [
    {
      "files": ["**/*.html"],
      "options": {
        "singleQuote": false,
        "tabWidth": 2
      }
    }
  ]
}
```

**Comment by tianyingchun** [comment]
what's progress of this issue, i run into this issue, it will break plugin`prettier-plugin-organize-imports`,

**Comment by joshmedeski** [comment]
No one has taken ownership to fix this issue.

For now, I suggest everyone expect `prettier-plugin-tailwindcss` can only be used on its own right now, your other prettier plugins aren't compatible.

After reviewing https://github.com/prettier/prettier/issues/10261 it seems like this plugin is highjacking the typescript parser and so any other plugin that also wants to interact with the same parser they are ignored. If someone understands this please feel free to experiment with rewriting this plugin so other plugins continue to work as expected.

**Comment by MusicOnline** [comment]
Both [`prettier-plugin-style-order`](https://www.npmjs.com/package/prettier-plugin-style-order) and [`prettier-plugin-css-order`](https://www.npmjs.com/package/prettier-plugin-css-order) do not work with prettier-plugin-tailwindcss.

**Comment by joshmedeski** [comment]
If you want a workaround, you could use the [prettier `--config` flag](https://prettier.io/docs/en/cli.html#--find-config-path-and---config) and have two different configs (using the [sharing configurations patter](https://prettier.io/docs/en/configuration.html#sharing-configurations) for consistent formatting).

This solution won't work with your IDE on saving, but it could work with a lint-stage solution.

```sh
prettier --config ./.prettierrc.tailwind.js --write .
prettier --config ./.prettierrc.other.js --write .
```

It's not a pretty solution, but I think it's possible for those that strongly want multiple plugin support.

I, personally, have decided to use the tailwind prettier plugin on its own for now to avoid adding this much complexity to my projects.

**Comment by bai** [comment]
> It's not a pretty solution, ...

I see what you did there.

**Comment by kxpro** [comment]
Also appears to be incompatible with https://github.com/prettier/plugin-php

**Comment by tianyingchun** [comment]
how about this issue

**Comment by devrsi0n** [comment]
> If you want a workaround, you could use the [prettier `--config` flag](https://prettier.io/docs/en/cli.html#--find-config-path-and---config) and have two different configs (using the [sharing configurations patter](https://prettier.io/docs/en/configuration.html#sharing-configurations) for consistent formatting).
> 
> This solution won't work with your IDE on saving, but it could work with a lint-stage solution.
> 
> ```shell
> prettier --config ./.prettierrc.tailwind.js --write .
> prettier --config ./.prettierrc.other.js --write .
> ```
> 
> It's not a pretty solution, but I think it's possible for those that strongly want multiple plugin support.
> 
> I, personally, have decided to use the tailwind prettier plugin on its own for now to avoid adding this much complexity to my projects.

Thanks for the idea, I made a lintstaged script to run eslint (with prettier tailwindcss) + prettier (with prettier sort imports), here is [an example](https://github.com/devrsi0n/chirpy/blob/083fe3a7a6a66d76c776c970504332128b1c3915/.lintstagedrc.js#L12)

**Comment by guilhermetod** [comment]
Also incompatible with [`prettier-plugin-organize-attributes`](https://github.com/NiklasPor/prettier-plugin-organize-attributes)

**Comment by jlarmstrongiv** [comment]
Any workarounds @guilhermetod ?

**Comment by manavm1990** [comment]
I for one can say that I can install and integrate: `@tailwindcss/forms` and it has 0 affect on this Prettier plugin. 

I don't particular care for the defaults put forth in the forms extension, so I don't usually use it. Just tried it out when I saw these issues.

As to all of the other plugins, I don't personally use all of those, but other ones such as standard prettier, or prettier for Jest I do use and never had any issue.

**Comment by kagurazaka-0** [comment]
I found a new workaround to make `@trivago/prettier-plugin-sort-imports` and `prettier-plugin-tailwindcss` work at the same time in React+TypeScript(works in vscode🎉).

1. if you do not have `prettier.config.js`, create a file and move the configuration to `prettier.config.js
2. copy the following into `prettier.config.js`.

```js
const pluginSortImports = require("@trivago/prettier-plugin-sort-imports")
const pluginTailwindcss = require("prettier-plugin-tailwindcss")

/** @type {import("prettier").Parser} */
const hackParser = {
  ... .pluginSortImports.parsers.typescript,
  parse: pluginTailwindcss.parsers.typescript.parse,
}

/** @type {import("prettier").Plugin} */
const hackedPlugin = {
  parsers: {
    typescript: hackParser,
  }
}

module.exports = {
  plugins: [hackedPlugin],
  // your settings
}
```

1. it will look like this

```tsx
// before
import { fuga } from ". /hoge"
import { Alert } from "~/components/atoms/Alert"

type Props = {}

export function Component(props: Props) {
  return (
    <div className="flex items-center justify-center w-[200px] h-64">
      <Alert />
    </div>
  )
}

// after
/*
config = {
  plugins: [hackedPlugin],
  tabWidth: 2,
  semi: false,
  printWidth: 120,
  arrowParens: "always",
  importOrder: ["^[~/]", "^[.. /]", "^[. /]"],
  importOrderSeparation: true,
}
*/

import { Alert } from "~/components/atoms/Alert"

import { fuga } from ". /hoge"

type Props = {}

export function Component(props: Props) {
  return (
    <div className="flex h-64 w-[200px] items-center justify-center">
      <Alert />
    </div>
  )
}
```

## References.

- [@trivago/prettier-plugin-sort-imports - parsers](https://github.com/trivago/prettier-plugin-sort-imports/blob/a5948970c56f532fd7d87d48950aebaff9ede07b/src/index.ts#L52-L65)
- [prettier-plugin-tailwindcss - createParser](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/blob/main/src/index.js#L128-L191)

## Underlying problem

After some investigation, I suspect that there is a problem with prettier's `getParsers()`.

 



  [https://github.com/prettier/prettier/blob/cd9955f1431ca3814ea9b713aa7275ceefa980d9/src/main/parser.js#L15-L25](https://github.com/prettier/prettier/blob/cd9955f1431ca3814ea9b713aa7275ceefa980d9/src/main/parser.js#L15-L25)

For example

```js
// prettier.config.js
const APlugin = {
  parsers: {
    typescript: ... ,
  },
}

const BPlugin = {
  parsers: {
    typescript: ... ,
  },
}

module.exports = {
  plugins: [APlugin, BPlugin],
  // ...
}
```


APlugin does not work when formatted with a ts file, and only BPlugin works.

I assume this is because the `parsers` in `getParsers()` are overwritten for each plugin.
I am currently investigating.

**Comment by nirtamir2** [comment]
https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/31#issuecomment-1195411734
@kagurazaka-0 Thank you! I try it and it works well!
Now I wait until I would be able to remove this workaround.

**Comment by linkb15** [comment]
> I don't know if it is also related to this, but I can't have `prettier-plugin-tailwindcss` working alongside `@tailwindcss/forms`. It says it doesn't find it.

I found a workaround on this one

Create a `tailwind.shared.config.js` contains all the things without `@tailwindcss/forms`

```js
/** @type {import("tailwindcss").Config}  */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {},
}
```

Then in normal `tailwind.config.js` add the plugins back.

```js
const config = require('./tailwind.shared.config.js')

/** @type {import("tailwindcss").Config}  */
module.exports = {
  ...config,
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
```

in `.prettierrc.js` use the config file without `@tailwindcss/forms`

```js
module.exports = {
  // other configs
  tailwindConfig: './tailwind.shared.config.js',
}
```

**Comment by rbluethl** [comment]
@kagurazaka-0 This works like a charm, thanks a lot!

**Comment by tusamni** [comment]
> Seems this one might be incompatible as well https://github.com/withastro/prettier-plugin-astro

Agreed, having this issue as well.

**Comment by mikesnoeren** [comment]
Are all these incompatibilities meant to be fixed at some point, or is this issues point to inform us that we can't use a combination of said plugins without odd workarounds?

**Comment by igitur** [comment]
> Are all these incompatibilities meant to be fixed at some point, or is this issues point to inform us that we can't use a combination of said plugins without odd workarounds?

I think the premise of your question is a bit misplaced. My experience with open-source software, unless funded by big sponsors, is that contributors submit patches mostly to solve their own problems. So either you have to get your hands dirty and submit a PR to solve this, or cross your fingers and hope that someone else has enough motivation to sacrifice their free time one day and do the work for you.

**Comment by hamatoyogi** [comment]
> > Seems this one might be incompatible as well https://github.com/withastro/prettier-plugin-astro
> 
> Agreed, having this issue as well.

same.

**Comment by scott-lc** [comment]
For those that are using `eslint` in conjunction with `prettier`, [eslint-plugin-tailwindcss](https://www.npmjs.com/package/eslint-plugin-tailwindcss) might be a viable alternative.

**Comment by tobiasriemenschneider** [comment]
> > > Seems this one might be incompatible as well https://github.com/withastro/prettier-plugin-astro
> > 
> > 
> > Agreed, having this issue as well.
> 
> same.

same.

**Comment by raszi** [comment]
It seems to be incompatible with https://github.com/ggascoigne/prettier-plugin-import-sort

**Comment by hotepp** [comment]
Would be very nice, if we had support for this one: https://github.com/prettier/plugin-pug
The markup used in `pug` can look like this: `h1(class="text-center font-serif")`, which is in terms of classes is the same as `HTML`. If anyone has a possible solution, I'd be very grateful. Thanks!

**Comment by raszi** [comment]
It seems to be incompatible with https://github.com/trivago/prettier-plugin-sort-imports

**Comment by cmalard** [comment]
Reading the [discussion here](https://github.com/prettier/prettier/pull/9417), according to Prettier's team, [re-ordering classes should not be done through Prettier](https://prettier.io/docs/en/rationale.html#what-prettier-is-_not_-concerned-about) but through ESLint, which is why they do not plan to solve it 😅
Should the effort be redirected to an ESLint plugin? (official support for the existing ones?)

**Comment by mattcroat** [comment]
I'm using SvelteKit and I can't make it work after reading the instructions and trying everything I've read here.

I provided a reproduction:
- [GitHub](https://github.com/mattcroat/svelte-tailwindcss)
- [StackBlitz](https://stackblitz.com/github/mattcroat/svelte-tailwindcss)

The `settings.json` file I use inside VS Code:

```json
"[svelte]": {
  "editor.defaultFormatter": "svelte.svelte-vscode"
}
```

Thank you! 🙏

**Comment by mattcroat** [comment]
I figured out the reason why I couldn't get it to work for SvelteKit and it's because for some reason it only works if you use `.prettier.config.cjs` instead of `.prettierrc`.

👎️ **.prettierrc**

```json
{
  "plugins": ["prettier-plugin-tailwindcss"]
}
```

👍️ **prettier.config.cjs**

```
module.exports = {
  plugins: [require('prettier-plugin-tailwindcss')],
}
```

Does anyone know the reason why? I thought it was the same and the [Prettier docs](https://prettier.io/docs/en/plugins.html) seem to corroborate it but I might not understand how it works.

> Strings provided to plugins are ultimately passed to require(), so you can provide a module/package name, a path, or anything else require() takes.

**Comment by mattcroat** [comment]
Here are the steps if you're using SvelteKit and `pnpm` to make it work:
1. `pnpm i -D prettier-plugin-tailwindcss`
2. `pnpm remove prettier-plugin-svelte`
3. Change your Prettier config from `.prettierrc` to `prettier.config.cjs`
4. Add the plugin

You can keep using the `svelte.svelte-vscode` formatter.

```json
"[svelte]": {
  "editor.defaultFormatter": "svelte.svelte-vscode"
}
```

**Comment by Princesseuh** [comment]
Hello, Erika from the Astro team here. Any idea when the current `main` will be released? 

[We contributed Astro support 2 months ago now](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/commit/76607ebf60cd514a018bc727d76a1b39e4f91e1b) and our users understandably keep asking us to support this. I know there was some needed changes after our PR, but it seems like those changes [were merged in a month ago](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/commit/3a6c6955a514c19cbfd992f4bad2a818074662e4).

If there's anything we can do to help get this released - please let us know and we'll gladly contribute!

**Comment by adamwathan** [comment]
@Princesseuh I _think_ it's still blocked by what @thecrypticace outlined here: https://github.com/tailwindlabs/prettier-plugin-tailwindcss/pull/87#issuecomment-1218432784

We're really busy trying to get Tailwind CSS v3.2 out the door this week and then out for a team retreat the following week, but we can look at this again the first week of November. One idea we might need to explore is multiple plugins, like a `prettier-plugin-tailwindcss-astro` plugin and a separate `pretter-plugin-tailwindcss-svelte` plugin or similar since it seems to be proving challenging to build something that works everywhere 😕

**Comment by jerriclynsjohn** [comment]
> 

@mattcroat I really appreciate this, and I did try but IDE kept showing `Saving '+page.svelte': Running 'Svelte for VS Code' Formatter` toast message while I was trying to save. If I try to navigate to a different file the toast message disappears and saves the file.

The formatting was successful by the end of the wait and consequent save did not have this problem. Just throwing this here to see if others faced this issue. I faced this issue both with my personal repo and also the repo shared by @mattcroat 

cc. @reinink

**Comment by TrevorLeeman** [comment]
@kagurazaka-0 Thanks for sharing. This looks like a promising solution, but I was personally not able to get it working. Continuously got this error in the Prettier output after making the change to the `prettier.config.js`:
```
Error formatting document. TypeError: Cannot read properties of undefined (reading 'map') at Object.getExperimentalParserPlugins
```
When only using `plugins: [require('prettier-plugin-tailwindcss')]` or `plugins: [require('@trivago/prettier-plugin-sort-imports')],` individually, Prettier works as expected.

**Comment by filipesmedeiros** [comment]
@TrevorLeeman are you using pnpm? I think I noticed the same thing when I moved to pnpm from yarn (v1). I'll try and get back to this thread with a result.

**Comment by TrevorLeeman** [comment]
> @TrevorLeeman are you using pnpm? I think I noticed the same thing when I moved to pnpm from yarn (v1). I'll try and get back to this thread with a result.
> 
> EDIT: confirmed. Reverting to Yarn solved the issue :)

Wow spot on, that was my problem as well. Thank you!

**Comment by gawlk** [comment]
Hiya, did anyone found a workaround when using pnpm ?

**Comment by reinink** [comment]
Hey folks! 👋

So just an update on the Prettier plugin compatibility situation. We've just released a new beta version of `prettier-plugin-tailwindcss` which improves (or at least we hope it does 😅) compatibility with specific other Prettier plugins, including:

- `prettier-plugin-svelte`
- `prettier-plugin-astro`
- `@trivago/prettier-plugin-sort-imports`
- `prettier-plugin-organize-imports`

We've taken a new approach with our Prettier plugin where we no longer bundle any third-party Prettier plugins (including the Svelte plugin — more on that below). And, through a safe list, we've explicitly added support for the above plugins which currently have known incompatibilities.

We've done this by automatically detecting if one of these plugins is installed and enabled in your project, and if it is, we do some magic behind the scenes in our plugin to make sure these plugins still work.

The one gotcha with this approach is that Prettier plugin autoloading is unreliable, because our plugin *must* come last in the list of plugins. For this reason, you'll need to explicitly disable the `pluginSearchDirs` option, and define each of your Prettier plugins in the `plugins` array:

```json5
// .prettierrc
{
  // ..
  "plugins": [
    "prettier-plugin-astro",
    "prettier-plugin-organize-imports",
    "prettier-plugin-tailwindcss" // MUST come last
  ],
  "pluginSearchDirs": false
}
```

For Svelte users, we no longer bundle the `prettier-plugin-svelte` plugin within our plugin, and you'll need install and enable it using the instructions above.

For Astro users, this new release supports `prettier-plugin-astro`, which you can install in the same way.

We've released this updated plugin as a beta version since we're not 100% sure on this approach quite yet, and would really appreciate your help testing it out. You can install it using the `beta` tag:

```sh
npm install prettier-plugin-tailwindcss@beta
```

Let me know how it goes! 💪

**Comment by darylknight** [comment]
No support for Twig :(

**Comment by gawlk** [comment]
Thank you @reinink 👏

For anyone struggling, this works with `pnpm`:

```js
plugins: [
    require.resolve('@trivago/prettier-plugin-sort-imports'),
    require('prettier-plugin-tailwindcss'),
],
```

**Comment by reinink** [comment]
Sup everyone! 👋

Just another update on the Tailwind CSS Prettier plugin. We've now added support for a bunch of other Prettier plugins and have released a new beta version for your testing pleasure.

Here's a complete list of all the plugins we added support for in this release:

- `@prettier/plugin-php`
- `@prettier/plugin-pug`
- `prettier-plugin-css-order`
- `prettier-plugin-import-sort`
- `prettier-plugin-jsdoc`
- `prettier-plugin-organize-attributes`
- `prettier-plugin-style-order`
- `prettier-plugin-twig-melody`

## Installing the beta

As previously mentioned, we need to do some shenanigans to get these plugins all working (I'm looking at you `@prettier/plugin-php`), so we'd really appreciate your help kicking the tires on this new version for us.

To install this latest beta, add it using npm:

```sh
npm install prettier-plugin-tailwindcss@beta
```

As mentioned in my previous comment, the one gotcha with this approach is that Prettier plugin autoloading is unreliable, because our plugin *must* come last in the list of plugins. For this reason, you'll need to explicitly disable the `pluginSearchDirs` option, and define each of your Prettier plugins in the `plugins` array:

```json5
// .prettierrc
{
  // ..
  "plugins": [
    "prettier-plugin-astro",
    "prettier-plugin-organize-imports",
    "prettier-plugin-tailwindcss" // MUST come last
  ],
  "pluginSearchDirs": false
}
```

## Other plugins

I think this covers all the Prettier plugins mentioned in this issue other than `@shufo/prettier-plugin-blade`, which unfortunately is more complicated since that plugin forks out to a different process and doesn't provide an AST — just a string. So we'd have to parse the whole Blade file ourselves to be able to sort classes within it, which is a much bigger undertaking.

**Comment by sameeranand1** [comment]
@reinink Can you add support for `@shopify/prettier-plugin-liquid`? This is for Shopify themes. https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/98

**Comment by reinink** [comment]
@sameeranand1 Done: #102 🤙

This has been released as `0.2.0-beta.3`.

**Comment by reinink** [comment]
Hello everyone, another update, we've just released v0.2.0, which includes all these plugin compatibility fixes.

You can install it using npm:

```
npm install prettier-plugin-tailwindcss@latest
```

We've also updated the readme to list all the Prettier plugins that we've added explicit support for:

https://github.com/tailwindlabs/prettier-plugin-tailwindcss#compatibility-with-other-prettier-plugins

With all this complete, I am going to close this issue as resolved. Thanks to everyone here for sharing information about incompatible plugins with us! 🙏

**Comment by mreduar** [comment]
So with this release already available is it still necessary to edit the `.prettierrc` file? I tried without editing but it doesn't work.
```js
// .prettierrc
{
  // ..
  "plugins": [
    "@prettier/plugin-pug",
    "prettier-plugin-organize-attributes",
    "prettier-plugin-tailwindcss" // It does not work if I put it here
  ],
  "pluginSearchDirs": false
}
```
and if I put `prettier-plugin-tailwindcss` last it doesn't work either.

**Comment by reinink** [comment]
@mreduar Hey, yes, you still to disable the `pluginSearchDirs` and list all your plugins in the `plugins` array, putting Tailwind CSS last (as per the [readme](https://github.com/tailwindlabs/prettier-plugin-tailwindcss#compatibility-with-other-prettier-plugins)).

If it's not working there is probably something else wrong. Feel free to create a _minimal_ reproduction and we can have a closer look 👍

**Comment by blooddrunk** [comment]
Looking forward for this to be compatible with [@ianvs/prettier-plugin-sort-imports](https://github.com/IanVS/prettier-plugin-sort-imports)

**Comment by bryanbarrios** [comment]
Hey @blooddrunk, this workaround worked for me:

```
const tailwindPlugin = require('prettier-plugin-tailwindcss');
const sortImportsPlugin = require('@ianvs/prettier-plugin-sort-imports');

module.exports = {
  parsers: {
    typescript: {
      ...tailwindPlugin.parsers.typescript,
      preprocess: sortImportsPlugin.parsers.typescript.preprocess,
    },
  },
  options: {
    ...sortImportsPlugin.options,
  },
};
```

Related to this [answer](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/9#issuecomment-1157359437).

**Comment by ramblehead** [comment]
Another breaking plugin is `prettier-plugin-jsdoc`

**Comment by reinink** [comment]
@ramblehead Hey! So we actually already have support for `prettier-plugin-jsdoc`, see here: https://github.com/tailwindlabs/prettier-plugin-tailwindcss#compatibility-with-other-prettier-plugins

**Comment by reinink** [comment]
@blooddrunk @bryanbarrios Just a heads up that we've also added support for `@ianvs/prettier-plugin-sort-imports`: https://github.com/tailwindlabs/prettier-plugin-tailwindcss/releases/tag/v0.2.3

**Comment by joejcox** [comment]
> Thank you @reinink 👏
> 
> For anyone struggling, this works with `pnpm`:
> 
> ```js
> plugins: [
>     require.resolve('@trivago/prettier-plugin-sort-imports'),
>     require('prettier-plugin-tailwindcss'),
> ],
> ```

Beautiful thanks! This worked for me (Next 13, pnpm)

**Comment by itz4rv** [comment]
@reinink 
> ## prettier-plugin-svelte
> We've bundled the `prettier-plugin-svelte` directly into `prettier-plugin-tailwindcss`, so if you'd like to use this plugin with Svelte, just uninstall `prettier-plugin-svelte` and everything should work as expected.

Isn't working with Prettier v3
'Prettier for VSCode' extension just completely stops formatting `.svelte` files

Adding `prettier-plugin-svelte` back and reloading VSCode formats both `.svelte` files and Tailwind class names

### `.prettierrc`
```
{
  "plugins": ["prettier-plugin-svelte", "prettier-plugin-tailwindcss"]
}
```

**Comment by thecrypticace** [comment]
@itz4rv This issue is 20 months old. The instructions have changed such that we no longer have to bundle Svelte and you include it in your plugins list like you'd do that with any other.

This is documented in the readme: https://github.com/tailwindlabs/prettier-plugin-tailwindcss#compatibility-with-other-prettier-plugins

**Comment by aurelienbobenrieth** [comment]
It is still not working for me:
`.prettierrc.cjs`
```js
module.exports = {
  trailingComma: "all",
  tabWidth: 2,
  semi: true,
  singleQuote: false,

  plugins: [
    "prettier-plugin-packagejson",
    "prettier-plugin-jsdoc",
    "@trivago/prettier-plugin-sort-imports",
    // Must be loaded last
    "prettier-plugin-tailwindcss",
  ],

  // prettier-plugin-tailwindcss
  tailwindAttributes: ["classProp"],

  // @trivago/prettier-plugin-sort-imports
  // https://github.com/trivago/prettier-plugin-sort-imports#usage
  importOrder: ["^#styles(.*)$", "<THIRD_PARTY_MODULES>", "^#(.*)$", "^[./]"],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderGroupNamespaceSpecifiers: true,
};
```

`package.json`
```json
"devDependencies": {
    "@tailwindcss/typography": "^0.5.10",
    "@trivago/prettier-plugin-sort-imports": "^4.3.0",
    "prettier": "3.1.0",
    "prettier-plugin-jsdoc": "^1.1.1",
    "prettier-plugin-packagejson": "^2.4.6",
    "prettier-plugin-tailwindcss": "^0.5.7",
    "tailwindcss": "^3.3.5",
    "typescript": "5.2.2",
    "vite": "^5.0.0",
  },
```

Based on : https://github.com/tailwindlabs/prettier-plugin-tailwindcss#compatibility-with-other-prettier-plugins

🤔

**Comment by jeannen** [comment]
Seems like it's not working when used with "prettier-plugin-organize-attributes"

**Comment by 4rvii** [comment]
> @itz4rv This issue is 20 months old. The instructions have changed such that we no longer have to bundle Svelte and you include it in your plugins list like you'd do that with any other.
> 
> This is documented in the readme: https://github.com/tailwindlabs/prettier-plugin-tailwindcss#compatibility-with-other-prettier-plugins

The issue was a problem with my VSCode, all worked after restart

**Comment by anburocky3** [comment]
Any update on this issue?
