### ISSUE TITLE
Top-level await is not available in the configured target environment

### ISSUE THREAD

**Issue by melihsd** [tailwindlabs/prettier-plugin-tailwindcss#313]
**What version of `prettier-plugin-tailwindcss` are you using?** 
v0.5.9

**What version of Tailwind CSS are you using?**
3.4.3

**What version of Node.js are you using?**
Bun 1.1.12

**What package manager are you using?**
Bun 1.1.12

**What operating system are you using?**
macOS

**Reproduction Steps**
Add an import declaration in any component :

    import { options } from 'prettier-plugin-tailwindcss';
   
**Describe your issue**
I noticed that my IDE sneaked in an wrong import from the prettier-plugin-tailwindcss lib and it caused my vite to completly fail to optimize.
Even if declaration is not used, it seems that import optimization does not take place here. 
Vite is unable to optimize just because of this import. This can be very frustrating since there is no real indication for it. 

**Error Message**
```
[vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/prettier-plugin-tailwindcss/dist/index.mjs:2353:46545: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
    at failureErrorWithLog (/Volumes/Work/[deducted]/node_modules/esbuild/lib/main.js:1651:15)
    at /Volumes/Work/[deducted]/node_modules/esbuild/lib/main.js:1059:25
    at /Volumes/Work/[deducted]/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by thecrypticace** [comment]
Hi! So the indication of a problem **is the build failure + error message**. If that wasn't enough that's a Vite problem — not a problem with our plugin.

We use top-level await because it's necessary for the implementation of our plugin. And, in general, you shouldn't be importing anything from `prettier-plugin-tailwindcss` in your project.
