### ISSUE TITLE
Ignore Prettier printWidth

### ISSUE THREAD

**Issue by GoulvenC** [tailwindlabs/prettier-plugin-tailwindcss#33]
It seems to me that the plugin does not respect the maximum characters per line (set by `printWidth`).

For example, when `printWidth` is set to 80 characters, this code :
```js
<a href="#" className="mt-8 bg-white border border-transparent rounded-md shadow px-5 py-3 inline-flex items-center text-base font-medium text-indigo-600 hover:bg-indigo-50">
  A stupidly long text just to illustrate my problem with the number of characters per line. I hope you are having a good day and that all is well in your lives!
</a>
```

Will be format to :
```js
<a
  href="#"
  className="mt-8 inline-flex items-center rounded-md border border-transparent bg-white px-5 py-3 text-base font-medium text-indigo-600 shadow hover:bg-indigo-50"
>
  A stupidly long text just to illustrate my problem with the number of
  characters per line. I hope you are having a good day and that all is
  well in your lives!
</a>
```

I'm using `"prettier": "^2.5.1"`, `"prettier-plugin-tailwindcss": "^0.1.4"`, `"tailwindcss": "^3.0.18"` and VS Code.

Thanks for your help, and all your work on this plugin !

**Comment by adamwathan** [comment]
Hey! Prettier does this even without this plugin (try uninstalling this plugin and formatting to see it), it doesn't add line breaks in strings like that. No plans to handle that as part of the scope of this plugin.

What I do personally is just enabled word wrap in my editor:

![image](https://user-images.githubusercontent.com/4323180/151704153-733f5886-9464-4962-8b55-ec6272a3357e.png)
