### ISSUE TITLE
Add compatibility with @trivago/prettier-plugin-sort-imports

### ISSUE THREAD

**Issue by RaniAgus** [tailwindlabs/prettier-plugin-tailwindcss#336]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.6.9

**What version of Tailwind CSS are you using?**

v3.4.16

**What version of Node.js are you using?**

v20.15.0

**What package manager are you using?**

pnpm

**What operating system are you using?**

For example: Linux (Ubuntu)

**Reproduction URL**

Just create a Remix project with shadcn/ui, add prettier, install both plugins and create this `.prettierrc`:

```
{
  "plugins": [
    "prettier-plugin-tailwindcss",
    "@trivago/prettier-plugin-sort-imports"
  ]
}
```

**Describe your issue**

Prettier is successfully sorting imports, but not able to sort tailwind classes.

**Comment by khallmark** [comment]
Tailwindcss has to be the last plugin in your list.

**Comment by RaniAgus** [comment]
Thanks!
