### ISSUE TITLE
What is the "recommended class order"?

### ISSUE THREAD

**Issue by michaelschufi** [tailwindlabs/prettier-plugin-tailwindcss#34]
Hi

First of all, thanks for the plugin! Glad to see Tailwind Labs improving the DX more and more.

The README states:
> A Prettier plugin for Tailwind CSS v3.0+ that automatically sorts classes based on **our recommended class order.**

I could not find this in the Tailwind CSS documentation. Could you please link to it? Or is this documented somewhere else?

**Comment by reinink** [comment]
Hey! You can find this explained in our announcement blog post about this plugin:

https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted

I've also added a link to this in the readme: d3c66e0d6c7337950bc1550b945cf8a54f1b967e

Hope that helps! 👍

**Comment by michaelschufi** [comment]
Awesome, thank you!
