### ISSUE TITLE
bg-* classes before p-* and m-* classes

### ISSUE THREAD

**Issue by wagerfield** [tailwindlabs/prettier-plugin-tailwindcss#35]
In the [Prettier plugin blog post](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted) it says:

> The actual order of the different utilities is loosely based on the box model, and tries to put high impact classes that affect the layout at the beginning and decorative classes at the end...

However the Prettier plugin is moving `bg-*` before padding `p-*` and margin `m-*` classes which is not what I would expect.

I would have thought that `bg-*` classes would fall into the "decorative" camp and should be placed after `m-*` and `p-*` classes.

For example:

```jsx
// before (expected)
<div className="p-4 bg-red-500 text-white" />

// after (plugin output)
<div className="bg-red-500 p-4 text-white" />
```

I don't want to be "that guy" bike shedding over class order, but I have always followed the same order/line of thinking as the blog post above—listing `bg-*` classes after display, padding and margin classes since they are more presentational/decorative.

Just wanted to see if this was the expected order and if not—is there any chance of moving the `bg-*` classes after padding and margin classes?

Thanks for your consideration.

**Comment by adamwathan** [comment]
Hey! My thinking on this one was just that background color affects even the padded area of an element, so working from the outside in it made sense to me that it would go margin -> border -> background -> padding.

Margin definitely comes first though (just tested):

```html
<div class="mt-5 border-2 bg-black p-4">
```

I don't feel super strongly about this really but also don't want to bike-shed over it either so not something I plan to change right now. Hope that explanation is at least helpful!

**Comment by CuriosBasant** [comment]
I don't like `bg-*` placed before `p-*` either. It is so inconvenient to find and change padding. Please move decorative classes like, `bg-*`, `text-*` *(color)*, `rounded-*`, etc, after the classes which affected the layout/size of the element.
