### ISSUE TITLE
Not working as expected with ESLint with formatOnSave

### ISSUE THREAD

**Issue by brunowego** [tailwindlabs/prettier-plugin-tailwindcss#38]
This is a great plugin, congrats!

Prettier is saving a different order from ESLint:

<img width="607" alt="Screen Shot 2022-02-03 at 20 30 29" src="https://user-images.githubusercontent.com/441774/152446861-9819c379-6925-4df0-ab03-2f75f8a14b3c.png">

<img width="603" alt="Screen Shot 2022-02-03 at 20 30 43" src="https://user-images.githubusercontent.com/441774/152446868-1e1e3fdb-2eb4-46db-9a1a-9c1b2c247e55.png">

My `prettier.config.cjs`:

```cjs
/**
 * @type {import('prettier').Options}
 */
const prettierConfig = {
  plugins: [require('prettier-plugin-tailwindcss')],
  semi: false,
  singleQuote: true,
  jsxSingleQuote: false,
  tailwindConfig: './tailwind.config.cjs',
}

module.exports = prettierConfig
```

And, my `.eslintrc.cjs`:

```cjs
const eslintRC = {
  extends: [
    'next/core-web-vitals',
    'plugin:tailwindcss/recommended',
    'plugin:storybook/recommended',
    'prettier',
  ],
  plugins: ['tailwindcss'],
}

module.exports = eslintRC
```

And, my `.vscode/settings.json`:

```json
{
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "tailwindCSS.includeLanguages": {
    "typescript": "javascript",
    "typescriptreact": "javascript"
  }
}
```

**Comment by brunowego** [comment]
As a workaround, I turn off the rule `tailwindcss/classnames-order` in `.eslintrc.cjs`:

```cjs
const eslintRC = {
  // ...
  rules: {
    'tailwindcss/classnames-order': 'off',
  },
}

module.exports = eslintRC
```

**Comment by adamwathan** [comment]
Hey! The `tailwindcss/classnames-order` ESLint rule is not something we made, that's a third-party thing I'd never seen until today so the order they are using is just different and not connected to the ordering we use in the Prettier plugin. Recommend disabling for sure if you want to use the Prettier plugin. If you'd like to use them together maybe the maintainer of that plugin can update it to use the same sort order we use here 👍🏻

**Comment by brunowego** [comment]
Great! Thanks for the quick answer! @adamwathan :)
