### ISSUE TITLE
To long lines

### ISSUE THREAD

**Issue by jrrmcalcio** [tailwindlabs/prettier-plugin-tailwindcss#39]
After i install it, all classes are set up together in a single line, and I used to put each on its own line, or at least group them up and divide them in multiple lines so I can scan them, but now they are all in a single line and I have to word wrap the document so I can see all of them, is there a way to divide them when there are lots of them or when the char length overpass the prettier length?

**Comment by adamwathan** [comment]
Hey! No way to configure this or anything I'm afraid and not something we plan to support. I recommend enabling word wrap, that's what I do myself 👍🏻  Alternatively you could of course not use this plugin and continue to format your class strings manually the way you like.

**Comment by OmarThinks** [comment]
I guess that this feature is really requested by many:  
https://github.com/tailwindlabs/tailwindcss/discussions/7763  
https://github.com/tailwindlabs/tailwindcss/discussions/11400  
https://github.com/tailwindlabs/tailwindcss/discussions/11514  
https://github.com/fundamentei/tailwrap  

Thanks. :)
