### ISSUE TITLE
Will not format classes within Blade files.

### ISSUE THREAD

**Issue by rappasoft** [tailwindlabs/prettier-plugin-tailwindcss#41]
I'm using VS Code and I have everything installed as required, `format on save` is on. 

When I save, I get an error on the bottom that says `Extension 'Prettier - code formatter' is configured as formatter but can not format 'Blade' files.`

I have this in my .prettierrc as noted in another issue, but it's not affecting anything:

```
{
    "overrides": [
        {
            "files": "*.blade.php",
            "options": {
                "parser": "html"
            }
        }
    ]
}
```

If I run `npx prettier --check resources/views` it states everything is formatted properly (which it's not)

Interestingly, if I change a blade file to be a plain HTML file,`format on save` still **does not** do anything, but running `npx prettier` will then find the issues.

What am I doing wrong?

Is there no support for the formatter in blade files within a Laravel project?

**Comment by zdarin** [comment]
Agree format blade files not as expected

**Comment by ndingeldein** [comment]
Blade formatting is probably outside the scope of this package but there is a package that has recently started to be developed to possibly finally have a good blade formatter.

https://github.com/ryangjchandler/prettier-plugin-blade

There is also the [Headwind](https://marketplace.visualstudio.com/items?itemName=heybourn.headwind) VS Code extension that essentially does the same thing as the [prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss)

**Comment by rappasoft** [comment]
@ndingeldein any idea why parsing the blade files as HTML in the prettier config does not work?

A decent chunk of people that use Tailwind are probably using it in Laravel projects.

**Comment by nwlr** [comment]
I have added https://github.com/prettier/plugin-php and added the above .prettierrc file and it works.

attention: the routes/web.php will be formatted very bad. i use it therefore only manually in the blade files.

restart vscode.

**Comment by rappasoft** [comment]
@nwlr My main goal is to just sort the Tailwind classes within a Blade file. You're saying installing your plugin and setting the blade parser to HTML makes it pick up the Tailwind classes using the tailwindcss-prettier plugin?

**Comment by Polfo** [comment]
It would be nice if there is a way to use this prettier-plugin-tailwindcss and have only the class="attributes" sorted. I don't know how to obtain that, in my case the result is that my laravel blade file is badly affected, probably by the html formatter.

**Comment by bradlc** [comment]
Hey @rappasoft. It looks like there's a couple things going on here.

> _When I save, I get an error on the bottom that says `Extension 'Prettier - code formatter' is configured as formatter but can not format 'Blade' files.`_

When using a parser override you may need to tell VS Code/Prettier that certain file types are "formatable". You can do this with the `prettier.documentSelectors` VS Code setting:

```
"prettier.documentSelectors": ["**/*.blade.php"]
```

> _If I run `npx prettier --check resources/views` it states everything is formatted properly (which it's not)_

This is very likely due to a Prettier [bug](https://github.com/prettier/prettier/issues/11141), whereby files that are not supported by default are ignored, even though there's a valid override. You can work around this by using `resources/views/**` instead of just `resources/views`:

```
npx prettier --check resources/views/**
```

I hope that helps, and if you run into any other issues please open a new issue with a reproduction 👍

**Comment by howdu** [comment]
There's a new blade plugin which's still a work-in-progress but works well - [prettier-plugin-blade](https://github.com/ryangjchandler/prettier-plugin-blade) and just set the parser to blade

```
"overrides": [
    {
      "files": "*.blade.php",
      "options": {
        "parser": "blade"
      }
    }
  ]
```

**Comment by Dibbyo456** [comment]
@howdu It works but vscode format on save does not work, prettier vscode extension is installed.
