### ISSUE TITLE
classNames order mismatch between VSCode Prettier extension and `prettier` CLI

### ISSUE THREAD

**Issue by bitmap** [tailwindlabs/prettier-plugin-tailwindcss#42]
Seeing similar errors to #19 & #21 in regards to class names order mismatches... In VS Code with the ESLint extension + Prettier extension, class names are formatted as expected and VSCode doesn't show any errors or warnings. However, when running `prettier` OR `eslint` (with prettier plugins) from the command line it's complaining that the classnames are in the wrong order... this is in direct contradiction to the [rules described in the blog post](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted), which says custom class names should come first.

```jsx
// Correct className in editor, no warnings shown...
<div className="wrapper grid h-full grid-cols-12 items-center gap-4">
```

`prettier` warning output...
```sh
→ npx prettier --check src   
Checking formatting...
[warn] src/components/header.tsx
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
```
... `eslint` warning output...
```sh
→ npx eslint src         
./src/components/header.tsx
  6:23  error  Replace `wrapper·grid·h-full·grid-cols-12·items-center·gap-4` with `grid·h-full·grid-cols-12·items-center·gap-4·wrapper`  prettier/prettier
```
As you can see, it wants to put `wrapper` at the end for some reason.

Here's my eslint config:
```
{
  "plugins": ["prettier"],
  "extends": ["next/core-web-vitals", "plugin:prettier/recommended"],
  "overrides": [
    {
      "files": ["**/*.ts?(x)"],
      "plugins": ["@typescript-eslint"],
      "extends": "plugin:@typescript-eslint/recommended",
    }
  ]
}
```

And relevant packages...

```
    "@typescript-eslint/eslint-plugin": "^5.10.2",
    "autoprefixer": "^10.4.2",
    "eslint": "8.8.0",
    "eslint-config-next": "12.0.10",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "postcss": "^8.4.6",
    "prettier": "2.5.1",
    "prettier-plugin-tailwindcss": "^0.1.4",
    "tailwindcss": "^3.0.18",
    "typescript": "4.5.5"
```

And for what it's worth, here's the very simple plugin for the custom `.wrapper` class...

```js
    plugin(({ addUtilities, theme }) => {
      const wrapper = theme("wrapper");

      addUtilities({
        ".wrapper": {
          width: "100%",
          maxWidth: wrapper.maxWidth,
          paddingLeft: wrapper.padding,
          paddingRight: wrapper.padding,
          marginLeft: "auto",
          marginRight: "auto",
        },
      });
    })
```

**Comment by adamwathan** [comment]
Hey! Since the `wrapper` class is defined using a Tailwind plugin it will be sorted alongside other Tailwind classes, and should appear as the last utility in your class list, before any modifiers like `hover` or `lg`.

I was explicit about that in the blog post:

![image](https://user-images.githubusercontent.com/4323180/152661338-af5a167f-d316-4f23-aa0d-65161120dd4f.png)

This is the correct order:

```
<div className="grid h-full grid-cols-12 items-center gap-4 wrapper">
```

Not sure how setting up Prettier with ESLint actually works, does it continuously run Prettier in the background to compare the output against your actual code and warn if anything is wrong? We don't have any official ESLint plugin or anything for class name order so unless that's how it works I wouldn't expect any warnings.

Going to close as "not a bug" (the order is right), but happy to continue the discussion here or in the Tailwind CSS discussions area 👍🏻

**Comment by bitmap** [comment]
Ah, missed that crucial bit! Sorry about that.

So prettier's eslint plugin is correct, but the eslint extension is contradicting it. I'll start digging there.

**Comment by bitmap** [comment]
I ended up moving this custom utility class out of the plugins in my tailwind config and into the `@layer utilities` layer in my CSS entry point. 

```css
@layer utilities {
  .wrapper {
    @apply mx-auto w-full max-w-screen-xl px-6;
  }
}
```
That seems to resolve any mismatches and puts it in the the intended order for custom classnames not added via a plugin:
```jsx
<div className="wrapper grid h-full grid-cols-12 items-center gap-4">
```

I assume this plugin isn't concerned with CSS files or the order of classes in the `@apply` directives. Which is _totally_ fine, I'm happier having `wrapper` first in the classlist. But I do wonder why the extension thought that `wrapper` was a custom class instead of a class added via a plugin, and the cli got it right. Maybe the extension is out of date.

Anyways, thanks @adamwathan, love the official plugin and the Tailwind ecosystem.
