### ISSUE TITLE
Class sorting is not working when arbitrary value is used

### ISSUE THREAD

**Issue by snax4a** [tailwindlabs/prettier-plugin-tailwindcss#43]
Hi,

I noticed that plugin is not sorting classes of the element if there is at least one arbitrary value.

This will not be sorted because of w-[200px] class used
```html
<div className="px-5 w-[200px] py-6 justify-center flex flex-col"></div>
```

This works:
```html
<div className="px-5 py-6 justify-center flex flex-col"></div>
```

**Comment by adamwathan** [comment]
Hey! Can't reproduce, arbitrary value classes are sorted as expected:

https://user-images.githubusercontent.com/4323180/152807067-5bea10e5-ece3-48a5-9348-6c163ac038a0.mov

If this is still an issue, can you open a new issue but include a reproduction repository so we can look deeper? Thanks.

**Comment by snax4a** [comment]
Hey @adamwathan,
I am using pnpm, so I had to configure this plugin inside prettier.config.js, maybe that is causing the problem
```js
module.exports = {
  plugins: ['prettier-plugin-tailwindcss'],
}
```

I will prepare minimal reproduction repository and open new issue then.
