### ISSUE TITLE
Co-locate extended theme classes?

### ISSUE THREAD

**Issue by adam-marshall** [tailwindlabs/prettier-plugin-tailwindcss#50]
I couldn't see if this has been requested before in the closed issues, sorry if this is a duplicate.

I know that custom classes are sorted first, so they are easy to see, which is a great idea.

However when the tailwind.config.js has its theme extended, e.g. extra spacing values to extend `w-`, or extra color values to extend `bg-`, `text-`, would it be possible to retain the sort order for those?

e.g. with the existing `w-96` the order would be
```
grid w-96 grid-cols-4 gap-2
```

if I extend spacing to add a `100: '25rem'` the order is 
```
w-100 grid grid-cols-4 gap-2
```

probably a better example is below, considering some red text with other utility classes:

```
mb-3 w-full rounded border-2 border-dashed py-5 px-3 text-center text-sm text-red-600
```

replacing with a custom theme color `error` you then get

```
text-error mb-3 w-full rounded border-2 border-dashed py-5 px-3 text-center text-sm
```

which feels worse because the `text-` utility classes are no longer co-located.

I know it is a custom class technically, but it seems completely different to the example given in the docs of `select2-dropdown`; its still in the TailwindCSS ecosystem.

**Comment by adamwathan** [comment]
Can you share a reproduction of what you're seeing? Anything added in the config should be treated as a regular Tailwind class and not a custom class. Tried to reproduce your results locally and I get this result as expected:

`grid w-100 grid-cols-4 gap-2`

Do you have your config file in a weird folder or anything that might cause it not to be picked up by the plugin?

**Comment by adam-marshall** [comment]
ah.. I am using a `tailwind.preset.js` file, which is then imported into individual `tailwind.config.js` files and used like

```
module.exports = {
  presets: [preset],
};
```

**Comment by adam-marshall** [comment]
it was named `tailwind.preset.js` in a nested directory (to go alongside common styling config).

if I rename it `tailwind.config.js` but keep it in the nested directory, it doesn't work.

if I kept it as `tailwind.preset.js` but move it to the top level, it doesn't work.

if I rename it `tailwind.config.js` but move it to the top level, then it works! 

and thankfully my individual separate tailwind.config.js files still seem to be taking effect, will monitor but that might be the solution.

**Comment by adamwathan** [comment]
Great! So it sounds like you need to follow the instructions here to configure a custom configuration path:

![image](https://user-images.githubusercontent.com/4323180/153589731-4f43520b-004e-401e-be8a-45325db84a9f.png)

**Comment by adam-marshall** [comment]
so the intention is to follow this sort of approach...https://nx.dev/guides/using-tailwind-css-with-angular-projects#configure-tailwind-css-for-an-application-with-buildable-or-publishable-libraries-as-dependencies

here is a snippet copied from that section...
```
// apps/app1/tailwind.config.js
const { createGlobPatternsForDependencies } = require('@nrwl/angular/tailwind');
const { join } = require('path');
const sharedTailwindConfig = require('../../libs/tailwind-preset/tailwind.config');

module.exports = {
  presets: [sharedTailwindConfig],
  content: [
    join(__dirname, 'src/**/!(*.stories|*.spec).{ts,html}'),
    ...createGlobPatternsForDependencies(__dirname),
  ],
};
```

so the multiple `tailwind.config.js` files for each app do seem to play nicely with each other - it seems to use the local app one first, and then that uses the preset... then it's just keeping the preset file named `tailwind.config.js` and at the top level means this plugin works too. 

so I think that works ok for me - feels intuitive enough.

thank you so much for the tip off 😃
