### ISSUE TITLE
`group` is sorted before custom classes

### ISSUE THREAD

**Issue by jenstornell** [tailwindlabs/prettier-plugin-tailwindcss#53]
I have a html element in a Vue installation.

```html
<div class="group task-group-item relative flex bg-red-500 text-neutral-900"></div>
```

It places `group` first, even before my custom class which is `task-group-item`. The custom class should be placed first according to the rules.

**Comment by bradlc** [comment]
Hey @jenstornell, thanks for reporting this! The issue will be fixed in the next release 👍
