### ISSUE TITLE
IDEA: Prettier tip - formatting all files

### ISSUE THREAD

**Issue by ACPK** [tailwindlabs/prettier-plugin-tailwindcss#56]
Including the code below in the Readme may help people who are looking to format their entire application.

`prettier --write .` or `prettier --write .`

**Comment by bradlc** [comment]
Hey @ACPK, thanks for your suggestion! I think we're going to leave this out for now. We already link to the Prettier website and if people are unfamiliar with Prettier they can read the documentation there 👍
