### ISSUE TITLE
.vue file support ?

### ISSUE THREAD

**Issue by m0dch3n** [tailwindlabs/prettier-plugin-tailwindcss#58]
The plugin is sorting within .html, .tsx files, but unfortunately not within .vue files.

**Comment by brandon-9** [comment]
https://www.youtube.com/watch?v=4SYv-1AHRbg Looks like it is.

**Comment by bradlc** [comment]
Hey @m0dch3n. The plugin works with `.vue` files and is tested as such. Unfortunately it is not going to be possible to debug and resolve the issue you are having with the information you have provided here. If you're still having issues please open a new issue, providing a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

**Comment by m0dch3n** [comment]
I found the issue, the project I checked out, had it's own vscode settings overriding my global settings...
