### ISSUE TITLE
Handling multiple TW configs (e.g. monorepo)

### ISSUE THREAD

**Issue by gekkedev** [tailwindlabs/prettier-plugin-tailwindcss#59]
I've noticed you can [specify the config path](https://github.com/tailwindlabs/prettier-plugin-tailwindcss#resolving-your-tailwind-configuration) in case the Tailwind config file isn't placed in the same directory. This also seems to work out-of-the-box in a monorepo where I'm receiving comments about my TWCSS config file (confirmation of the file being found?). Probably this is based on one of my TW configs (the class sorting, too), but I don't know which file it picked. Would it be possible to optionally specify the configs as array to apply them to subfolders? Running Prettier on every subfolder individually may be extensive. An interface could look like this:
```js
// prettier.config.js
module.exports = {
  tailwindConfig: [
    { directory: "./project1", config: "./project1/tailwind.config.js" } // applies the project's own config
    { directory: "./project2", config: "./project3/tailwind.config.js" } // applies a different project's config
  ]
}
```
This kind of configuration level could become very helpful if Prettier runs globally on a repo with one or many TWCSS configs. Even without this feature, it would be awesome to log by default which of the available TW files has been auto-detected (for debugging purposes). This helps with understanding which config the feedback while running prettier applies to.

**Comment by adamwathan** [comment]
Hey! Prettier already supports using a different config in each directory I think doesn't it? Does it work if you just add a `pretter.config.js` file to each subdirectory that needs to specify the Tailwind config?

**Comment by bradlc** [comment]
Hey @gekkedev. It is not possible for plugins to provide Prettier configuration options that accept array or object values, so I'm not sure how we would provide something like this. Also, as Adam said, you can already achieve this using multiple Prettier config files, for example:

```
my-app/
├─ project-1/
│  ├─ prettier.config.js
│  ├─ tailwind.config.js
├─ project-2/
│  ├─ prettier.config.js
├─ project-3/
│  ├─ tailwind.config.js
```

```js
// project-1/prettier.config.js
module.exports = {
  tailwindConfig: './tailwind.config.js',
}

// project-2/prettier.config.js
module.exports = {
  tailwindConfig: '../project-3/tailwind.config.js',
}
```

If you want to share common options you could create a config in the root that you import into each project's config:

```js
// prettier.config.js
module.exports = {
  singleQuote: true,
}

// project-1/prettier.config.js
module.exports = {
  ...require('../prettier.config.js'),
  tailwindConfig: './tailwind.config.js',
}

// project-2/prettier.config.js
module.exports = {
  ...require('../prettier.config.js'),
  tailwindConfig: '../project-3/tailwind.config.js',
}
```

Also, with this kind of setup you don't need to run Prettier separately in each directory. Prettier will automatically use the correct config for each file based on its path. For example `project-1/example.html` will use `project-1/prettier.config.js` and `project-2/example.html` will use `project-2/prettier.config.js`

I hope that helps!
