### ISSUE TITLE
I could install this package with wp-prettier

### ISSUE THREAD

**Issue by shivapoudel** [tailwindlabs/prettier-plugin-tailwindcss#60]
Please can you support `wp-prettier` as we could not install it on our environment. https://github.com/WordPress/gutenberg/blob/929d32e9ab827b23579add6e7e81f517f5080900/package.json#L196
![image](https://user-images.githubusercontent.com/3774827/153747339-6a3eb426-0cb5-41ef-aa6a-d1291fa0629a.png)

**Comment by bradlc** [comment]
Hi @shivapoudel. The plugin will work fine with `wp-prettier`, but it requires at least version `2.2.0` of `prettier`, and you're using `wp-prettier@2.0.5`, which is a fork of `prettier@2.0.5`. It looks like there's a beta version of `wp-prettier` (`2.2.1-beta-1`) that works though. You will need to use `--force` or `--legacy-peer-deps` as mentioned in the error message, as `prettier-plugin-tailwindcss` lists `prettier` as a peer dependency. Here's what I did to get it working:

```
npm install -D --force prettier@npm:wp-prettier@2.2.1-beta-1 prettier-plugin-tailwindcss
```

Hope that helps!

**Comment by shivapoudel** [comment]
@bradlc That works nicely, my friend :)

One more question, if I have `tailwind.config.js` in the project root then I don't have to add `tailwindConfig` in the prettier config right because I just extend like this for faster-bootstrapping stuff.

```js
// Import the default config file and expose it in the project root.
// Useful for editor integrations.
module.exports = require( '@wordpress/prettier-config' );
```
