### ISSUE TITLE
Css class sorting changes if formatted on save or by a script

### ISSUE THREAD

**Issue by francoisromain** [tailwindlabs/prettier-plugin-tailwindcss#61]
Hello, 
With a specific config, the css classes order is different when formatted on save and when formatted by a script.

I made a repo with a minimal reproduction to show the bug: https://github.com/francoisromain/bug-svelte-tailwind

To reproduce the bug, in VS Code:

- Clone this repo
- Install the dependencies : `npm i`
- Install the required VS Code extensions : `svelte.svelte-vscode`, `dbaeumer.vscode-eslint`, `esbenp.prettier-vscode` and `bradlc.vscode-tailwindcss`.
- Open the file `src/routes/index.svelte` and save the file. The order of the css classes changes.
- Run `npm run format`. The order of the css classes changes again.

If we remove the `boxShadow` property in `tailwind.config.cjs`, the css order stays the same when formatted on save and by a script.

**Comment by bradlc** [comment]
> _However, if I add a `prettier.config.cjs` file, it works fine._

Brilliant, thanks for confirming! I'll close this since your issue is resolved 👍
