### ISSUE TITLE
Incorrectly ordered text-* classes

### ISSUE THREAD

**Issue by elliotdavies** [tailwindlabs/prettier-plugin-tailwindcss#69]
**What version of `prettier-plugin-tailwindcss` are you using?**

0.1.8 with Prettier 2.6.2

**What version of Tailwind CSS are you using?**

3.0.24

**What version of Node.js are you using?**

16.10.0

**What package manager are you using?**

npm 7.24.0

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/elliotdavies/prettier-plugin-tailwindcss-example

See `src/test.html` for examples of actual/expected behaviour. Run `npm install` and `npm run format` to see the behaviour.

You can use the included `shell.nix` or bring your own Node / npm.

**Describe your issue**

1. `text-*` classes such as `text-md` or `text-red` are appearing before "layout" classes like `m-2`. I would expect them to appear afterwards, per https://github.com/tailwindlabs/prettier-plugin-tailwindcss
2. `text-*` classes that use colours defined in the TW config file are not being kept together with other `text-*` classes. For example `text-md` is being separated from `text-bespoke-color` (where `bespoke-color` is defined in the config). I would expect all the `text-*` classes to be grouped

**Comment by bradlc** [comment]
Hey @elliotdavies. Thanks for providing a reproduction. I have addressed both of your issues below:

1. `text-md` and `text-red` are not default Tailwind classes, and you don't have these configured as custom classes either. All non-Tailwind classes like these are moved to the front of the class list, so what you're seeing is expected.
2. Again, `text-md` is not a Tailwind class so this is moved to the front of the list as expected.

I hope that helps!
