### ISSUE TITLE
VSCode support for .erb files

### ISSUE THREAD

**Issue by drale2k** [tailwindlabs/prettier-plugin-tailwindcss#7]
It would be great to add documentation on how to configure VSCode to work with templating languages like ruby .erb files.

**Comment by weavermedia** [comment]
Yes please!

```
class: "text-white bg-sky-700"
:class => "text-white bg-sky-700"
```

**Comment by reinink** [comment]
Hey there! So, this is a Prettier plugin, not a VSCode plugin, so I don't think it makes sense to include this in the documentation for this plugin.

That said, if you're looking for help getting ERB templates working with VSCode, I'd recommend checking out this plugin: https://marketplace.visualstudio.com/items?itemName=SarahRidge.vscode-ruby-syntax
