### ISSUE TITLE
[v0.1.9] Unwanted removal of leading whitespace for concatenated class

### ISSUE THREAD

**Issue by bennettdams** [tailwindlabs/prettier-plugin-tailwindcss#71]
**What version of `prettier-plugin-tailwindcss` are you using?**

`v0.1.9`

**What version of Tailwind CSS are you using?**

`v3.0.24`

**What version of Node.js are you using?**

`v16.13.0`

**What package manager are you using?**

npm

**What operating system are you using?**

Windows

**Reproduction URL**

https://github.com/bennettdams/tailwind-prettier-whitespace-bug

**Describe your issue**

Version `v0.1.9` introduced a change for frameworks like React that will introduce "bugs".

Here is a basic example. When a class consists of multiple concatenated strings, the plugin now removes the leading whitespace:

```diff
function Test() {
-      return <div className={"text-white" + " bg-red-100"} />;
+      return <div className={"text-white" + "bg-red-100"} />;
}
```

I use this format of concatenated strings for visibility when there are a lot of classes, e.g.:

```
className={
  'inline-flex items-center' +
  ' rounded-md p-2 shadow-sm focus:outline-none focus:ring-2 focus:ring-purple-600 focus:ring-opacity-50' +
  ' bg-dlila text-white transition duration-75 ease-in-out hover:bg-dorange' +
  ' disabled:cursor-not-allowed disabled:bg-gray-200'
}
```

**Comment by dargmuesli** [comment]
For me it wants to replace this

```diff
function Test() {
-      :class="['button', ...(buttonClass ? [buttonClass] : [])].join(' ')"
+      :class="['button', ...(buttonClass ? [buttonClass] : [])].join('')"
}
```

... which is certainly not what _I_ want :sweat_smile:

**Comment by bradlc** [comment]
Thanks for reporting this @bennettdams! For now we have published a new release (`v0.1.10`) that removes the whitespace removal feature while we consider solutions to the issues you were seeing 👍

**Comment by thevuong** [comment]
I like the feature of eliminating repeated spaces as well as the same class names. The problem of long class names can be used `clsx` library. I hope the removed feature will reappear in the new version.

**Comment by karlhorky** [comment]
Any new plans for this? Maybe reintroducing the removed feature as a (default-off) option for the plugin as [has been suggested by the community](https://github.com/tailwindlabs/tailwindcss/discussions/7560#discussioncomment-4903521)?

We've had a number of new duplicate whitespace commits creep into our codebase, hard to manually review these mistakes.

**Comment by stefanosandes** [comment]
This vscode plugin may be useful for anyone wanting to do so: https://github.com/heybourn/headwind
