### ISSUE TITLE
Support formatting template literals inside functions (@netlify/classnames-template-literals)

### ISSUE THREAD

**Issue by aalises** [tailwindlabs/prettier-plugin-tailwindcss#73]
**Describe your issue**

Hello! we are using https://github.com/netlify/classnames-template-literals to keep a high number of classes sanitized and legible e.g.

```ts
import ctl from "@netlify/classnames-template-literals";

export const searchBarWrapper = ctl(`
  mt-2 
  mx-4
  p-4 
  border-b 
  border-gray-300
`);
```

Any chance that we could support the plugin to also sort the classes inside these functions?

**What version of `prettier-plugin-tailwindcss` are you using?**
Latest

**What version of Tailwind CSS are you using?**
Latest

**What version of Node.js are you using?**
v14.0.0

**What package manager are you using?**
Yarn

**What operating system are you using?**
macOS

**Comment by bradlc** [comment]
Hey @aalises. As this is a feature request and not an issue I am going to close it in favour of the existing [discussion](https://github.com/tailwindlabs/tailwindcss/discussions/7558) over on the `tailwindcss` repo. Please feel free to leave any comments you have there 👍
