### ISSUE TITLE
Textarea elements are not self-closed when using bind:value

### ISSUE THREAD

**Issue by harshmandan** [tailwindlabs/prettier-plugin-tailwindcss#81]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.1.10

**What version of Tailwind CSS are you using?**

v3.0.24

**What version of Node.js are you using?**

v16.13.0

**What package manager are you using?**

npm

**What operating system are you using?**

macOS, Windows

**Describe your issue**

Please see the example code to understand the problem:

`TextArea.svelte` (Before saving)
```
<script>
export let value = ''
</script>

<textarea custom-data=". . . . . . . . . . . . . . . . . . . . . . . ." bind:value/>
```

`TextArea.svelte` (After saving)
```
<script>
export let value = ''
</script>

<textarea
 custom-data=". . . . . . . . . . . . . . . . . . . . . . . ."
 bind:value>
</textarea>
```

**Problem**: 

If there are some attributes which push the closing `textarea` tag in the next line, svelte and eslint - both show the error: `A <textarea> can have either a value attribute or (equivalently) child content, but not both svelte(textarea-duplicate-value)`

**Expected behavior**:

`textarea` element should not use a closing tag, instead just self-close when `bind:value` attribute is present 

`.prettierrc` config:
```
{
  "tabWidth": 2,
  "printWidth": 80,
  "singleQuote": true,
  "trailingComma": "all",
  "semi": false,
  "arrowParens": "always",
  "htmlWhitespaceSensitivity": "ignore",
  "quoteProps": "consistent",
  "endOfLine": "auto",
  "bracketSameLine": true,
  "svelteStrictMode": true,
  "svelteIndentScriptAndStyle": false,
  "svelteAllowShorthand": true,
  "plugins": [
    "./node_modules/prettier-plugin-tailwindcss"
  ],
  "tailwindConfig": "./tailwind.config.cjs",
  "overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
}


```

**Comment by adamwathan** [comment]
Hey! I think you meant to open this on the Svelte Prettier plugin repo probably? We don’t do anything to Svelte syntax in this plugin, unless I’m misunderstanding.

**Comment by adamwathan** [comment]
Going to close this one, we do include the Svelte Prettier plugin within this project but we don’t do any formatting of Svelte code ourselves. Any issue would be with that plugin, and when something is fixed we just need to update our bundled version.
