### ISSUE TITLE
Sorting not working properly when there is custom defined screen modifier

### ISSUE THREAD

**Issue by HananMehmood5** [tailwindlabs/prettier-plugin-tailwindcss#89]
**What version of `prettier-plugin-tailwindcss` are you using?**

0.1.13

**What version of Tailwind CSS are you using?**

2.7.1

**What version of Node.js are you using?**

16.15.1

**What package manager are you using?**

yarn

**What operating system are you using?**

macOS

**Reproduction Steps**

In tailwind config, extend it by having following
```
...
extend: {
      screens: {
        xs: '480px'
      }
},
...
```

Now when I have the following code:
```
<div className="grid grid-cols-1 gap-8 xs:grid-cols-2 lg:grid-cols-4"> ... </div>
```
When i save the code, prettier sorts the code and it turns out to be:
```
<div className="grid grid-cols-1 gap-8 lg:grid-cols-2 xs:grid-cols-4"> ... </div>
```
Which is disturbing the styles as xs preceeds the styling. 

**Describe your issue**

Prettier is now working properly when we define custom screen size identifiers as in example above. As it makes them to the last which is creating issues.

**Comment by bradlc** [comment]
Hey @HananMehmood5. The reason (and solution) for this is explained in the [Tailwind CSS documentation](https://tailwindcss.com/docs/screens#adding-smaller-breakpoints):

> _If you want to add an additional small breakpoint, you can’t use `extend` because the small breakpoint would be added to the end of the breakpoint list, and breakpoints need to be sorted from smallest to largest in order to work as expected with a min-width breakpoint system._
>
> _Instead, override the entire screens key, re-specifying the default breakpoints:_
>
> ```js
> const defaultTheme = require('tailwindcss/defaultTheme')
> 
> module.exports = {
>   theme: {
>     screens: {
>       'xs': '475px',
>       ...defaultTheme.screens,
>     },
>   },
>   variants: {},
>   plugins: [],
> }
> ```

I hope that helps!

**Comment by richardMoneyMonk** [comment]
```
  screens: {
      ...defaultTheme.screens,
      'xs': '475px',
    }
```

Else you will override.
