### ISSUE TITLE
Incompatible with `@trivago/prettier-plugin-sort-imports`

### ISSUE THREAD

**Issue by GraxMonzo** [tailwindlabs/prettier-plugin-tailwindcss#9]
`prettier` version: 2.5.1
`@trivago/prettier-plugin-sort-imports` version: 3.1.1
`tailwindcss` version: 2.2.17

My .prettierrc.json
```json
{
  "singleQuote": true,
  "jsxSingleQuote": true,
  "importOrder": [
    "<THIRD_PARTY_MODULES>",
    "^@/types$",
    "^@/types/(.*)$",
    "^@/api$",
    "^@/api/(.*)$",
    "^@/config/(.*)$",
    "^@/context/(.*)$",
    "^@/pages/(.*)$",
    "^@/components/(.*)$",
    "^@/hooks/(.*)$",
    "^@/helpers/(.*)$",
    "^@/images/(.*)$",
    "^@/locales/(.*)$",
    "^[./]",
    "^./tailwind.css$",
    "^.*.css$"
  ],
  "importOrderSeparation": true,
  "importOrderCaseInsensitive": false,
  "tailwindConfig": "./tailwind.config.js"
}
```
Only import sorting works

**Comment by reinink** [comment]
Hey! Thanks for reporting this. I've created a new issue (#31) dedicated to keeping track of Prettier plugins that are not compatible with this plugin. Closing this issue in favor of that 👍

**Comment by reinink** [comment]
PS — please feel free to share this as a comment in that thread, it would be great to have it there for quick reference.

**Comment by giacomoferretti** [comment]
@Mattinton thanks for the workaround, I had to make a small change because it was giving me `TypeError: Cannot read properties of undefined (reading 'map')`.

```js
const tailwindPlugin = require("prettier-plugin-tailwindcss");
const sortImportsPlugin = require("@trivago/prettier-plugin-sort-imports");

module.exports = {
  parsers: {
    typescript: {
      ...tailwindPlugin.parsers.typescript,
      preprocess: sortImportsPlugin.parsers.typescript.preprocess,
    },
  },
  options: {
    ...sortImportsPlugin.options,
  },
};
```

**Comment by reinink** [comment]
Update on this one — we've added support for this plugin in the latest (beta) version of our Prettier plugin. You can read more about that here: https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/31#issuecomment-1312202554

**Comment by unclejustin** [comment]
In case anyone else runs into this. If you import a type with the same name as an exported function. Prettier will throw this exact same error. 

Example: 

```ts
import { RandomName } from './page'

// other code

export default function  RandomName () {
// more code
}
```
