### ISSUE TITLE
Does not seem to support .liquid files

### ISSUE THREAD

**Issue by sodevious** [tailwindlabs/prettier-plugin-tailwindcss#98]
Attempting to format a `.liquid` file does not have any effect from this pluigin, but the exact file renamed to a `.html` extension does work. Possible to get support for `.liquid` files? (used in Shopify themes)

**Comment by bradlc** [comment]
Hey! Thanks for reporting this. We have an issue (https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/31) dedicated to keeping track of Prettier plugins that are not compatible with this plugin. Closing this issue in favor of that 👍

Please feel free to post this incompatibility with `@shopify/prettier-plugin-liquid` in that issue, it would be great to have it there for quick reference.

**Comment by reinink** [comment]
Just a follow up on this issue — we've just added support for the `@shopify/prettier-plugin-liquid` plugin. More details can be found in this issue: https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/31#issuecomment-1324280713
